### ISSUE TITLE
docker instance does not start anymore: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: delete from `cache`)

### ISSUE THREAD

**Issue by jrhbcn** [alexjustesen/speedtest-tracker#1066]
**Describe the bug**
After an update, the docker instance does not start anymore 

**To Reproduce**
just start container with `docker compose up -d speedtest-tracker`

**Expected behavior**
Container starts properly

**Environment (please complete the following information):**
Using docker image ghcr.io/alexjustesen/speedtest-tracker:latest as per site instructions with mariadb extra container. Everything worked fine just before the upgrade to mariadb or speedtracker.

**Logs**
I see this error in the logs:

```
🧹  Clearing any previous caches...
[2024-01-21 10:14:36] production.ERROR: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: delete from `cache`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: delete from `cache`) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:822)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(976): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(955): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(778): Illuminate\\Database\\Connection->handleQueryException()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\\Database\\Connection->run()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(557): Illuminate\\Database\\Connection->affectingStatement()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3615): Illuminate\\Database\\Connection->delete()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php(342): Illuminate\\Database\\Query\\Builder->delete()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(693): Illuminate\\Cache\\DatabaseStore->flush()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Console/ClearCommand.php(69): Illuminate\\Cache\\Repository->__call()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Cache\\Console\\ClearCommand->handle()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#15 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(40): Illuminate\\Console\\Command->runCommand()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(37): Illuminate\\Console\\Command->callSilent()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Foundation\\Console\\OptimizeClearCommand->Illuminate\\Foundation\\Console\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Factory.php(58): Illuminate\\Console\\View\\Components\\Task->render()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(41): Illuminate\\Console\\View\\Components\\Factory->__call()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Illuminate\\Foundation\\Console\\OptimizeClearCommand->Illuminate\\Foundation\\Console\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(41): Illuminate\\Support\\Collection->each()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Console\\OptimizeClearCommand->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#31 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#33 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#34 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#35 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#37 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#38 {main}

[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(83): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(48): Illuminate\\Database\\Connectors\\Connector->tryAgainIfCausedByLostConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1319): call_user_func()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(601): Illuminate\\Database\\Connection->getPdo()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(976): Illuminate\\Database\\Connection->runQueryCallback()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(955): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(778): Illuminate\\Database\\Connection->handleQueryException()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(593): Illuminate\\Database\\Connection->run()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(557): Illuminate\\Database\\Connection->affectingStatement()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3615): Illuminate\\Database\\Connection->delete()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php(342): Illuminate\\Database\\Query\\Builder->delete()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(693): Illuminate\\Cache\\DatabaseStore->flush()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Console/ClearCommand.php(69): Illuminate\\Cache\\Repository->__call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Cache\\Console\\ClearCommand->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#24 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(40): Illuminate\\Console\\Command->runCommand()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(37): Illuminate\\Console\\Command->callSilent()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Foundation\\Console\\OptimizeClearCommand->Illuminate\\Foundation\\Console\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Factory.php(58): Illuminate\\Console\\View\\Components\\Task->render()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(41): Illuminate\\Console\\View\\Components\\Factory->__call()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Illuminate\\Foundation\\Console\\OptimizeClearCommand->Illuminate\\Foundation\\Console\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php(41): Illuminate\\Support\\Collection->each()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Console\\OptimizeClearCommand->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#40 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#42 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#43 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#44 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#46 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#47 {main}
"}

In Connection.php line 822:

  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: delete f
  rom `cache`)


In Connector.php line 65:

  SQLSTATE[HY000] [2002] Connection refused

```

Any ideas how to solve this? Thanks.

**Comment by alexjustesen** [comment]
Restart the container (speedtest tracker only) and see if it comes back up, sometimes the database isn't ready when the container starts up.

Additionally check your tables in your MariaDB instance, you should see a `cache` table, if not we'll dig deeper.

**Comment by crower19** [comment]
I have similar problem. 

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speed_tracker.cache' doesn't exist (Connection: mysql, SQL: delete from `cache`)             
                                                                               
In Connection.php line 601:`

I remove the mariaDB and speed tracker, also the persistent storages and recrete all from scratch but i get the same error.

**Comment by alexjustesen** [comment]
Thanks, not sure when I'll be able to work on this. On vacation.

**Comment by jrhbcn** [comment]
No worries, just let us know if you need anything from us when you have the time to look at it. Thank you,

**Comment by crower19** [comment]
same here. no worries and enjoy your holidays.

**Comment by wiseman13** [comment]
FYI I was able to get mine up and going again with all historic data by changing CACHE_DRIVER from 'database' to 'file'. That will get me going for now and I hope that helps others with the issue for a work around.

**Comment by jrhbcn** [comment]
Many thanks @wiseman13. I can confirm that adding that CACHE_DRIVER option also fixed the problem for me. Let's keep this issue open in case @alexjustesen just wants to have a look at it.

**Comment by crower19** [comment]
Yes, setting CACHE_DRIVER to "file" value fix the problem. Now I can run the container but the web is sooooooo slow now.

**Comment by jrhbcn** [comment]
The same error just pop-up again in my setup. I have both CACHE_DRIVER=file in my docker-compose file and also in /config/.env but now it does not seem to work-around the problem anymore.

Anyone else with the same thing?

**Comment by alexjustesen** [comment]
Having scheduled cache pruning likely cropped up some config issues.

You have the option to use `file` or `database` as your cache driver. While `file` works well in simple setups you can run into file permissions issues so I recommend setting it to `database` and then restarting your container. #1084 changes the default driver to `database` at the config level so you can entirely omit this from your env configs.

**ALSO** make sure you have this config only set in one place, either in your `.env` file or passed into the container as an environment variable.

**Comment by alexjustesen** [comment]
More more debug comment, run `php artisan db:show` in your container's console and you can see the output of tables in your database. You should see a `cache` and `cache_locks` table:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/d6876346-506b-439b-8ec0-da55f2ab6214)

**Comment by jrhbcn** [comment]
Thanks @alexjustesen ,

I made sure I deleted the settings from both my docker compose file and the .env file in config so going back to "database" cache instead of file. Restarted the container and now everything works again

The command `php artisan db:show` shows both tables, as you mentioned.

Many thanks!
