### ISSUE TITLE
DB Migration Error with 0.16.1

### ISSUE THREAD

**Issue by thespad** [alexjustesen/speedtest-tracker#1165]
**Describe the bug**
Using postgres backend, on upgrade from 0.15.4 to 0.16.1:

```text
[2024-02-19 22:16:13] production.ERROR: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "results_bad_json" does not exist
```

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Docker (Linuxserver image)
-  Architecture: adm64
 - Browser: N/A
 - Version; 0.16.1

**Logs**
```text
speedtest-tracker  | [2024-02-19 22:14:26] production.ERROR: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "results_bad_json" does not exist
speedtest-tracker  | 
speedtest-tracker  | LINE 1: select count(*) as aggregate from "results_bad_json"
speedtest-tracker  |                                           ^ (Connection: pgsql, SQL: select count(*) as aggregate from "results_bad_json") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"results_bad_json\" does not exist
speedtest-tracker  | LINE 1: select count(*) as aggregate from \"results_bad_json\"
speedtest-tracker  |                                           ^ (Connection: pgsql, SQL: select count(*) as aggregate from \"results_bad_json\") at /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
speedtest-tracker  | [stacktrace]
speedtest-tracker  | #0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback()
speedtest-tracker  | #1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\\Database\\Connection->run()
speedtest-tracker  | #2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2751): Illuminate\\Database\\Connection->select()
speedtest-tracker  | #3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2740): Illuminate\\Database\\Query\\Builder->runSelect()
speedtest-tracker  | #4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3294): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
speedtest-tracker  | #5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2739): Illuminate\\Database\\Query\\Builder->onceWithColumns()
speedtest-tracker  | #6 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3221): Illuminate\\Database\\Query\\Builder->get()
speedtest-tracker  | #7 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3149): Illuminate\\Database\\Query\\Builder->aggregate()
speedtest-tracker  | #8 /app/www/database/migrations/2024_02_18_100000_results_bad_json_table.php(50): Illuminate\\Database\\Query\\Builder->count()
speedtest-tracker  | #9 /app/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(493): Illuminate\\Database\\Migrations\\Migration@anonymous->up()
speedtest-tracker  | #10 /app/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(410): Illuminate\\Database\\Migrations\\Migrator->runMethod()
speedtest-tracker  | #11 /app/www/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
speedtest-tracker  | #12 /app/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(418): Illuminate\\Database\\Connection->transaction()
speedtest-tracker  | #13 /app/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->runMigration()
speedtest-tracker  | #14 /app/www/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
speedtest-tracker  | #15 /app/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(756): Illuminate\\Console\\View\\Components\\Task->render()
speedtest-tracker  | #16 /app/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->write()
speedtest-tracker  | #17 /app/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(181): Illuminate\\Database\\Migrations\\Migrator->runUp()
speedtest-tracker  | #18 /app/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(124): Illuminate\\Database\\Migrations\\Migrator->runPending()
speedtest-tracker  | #19 /app/www/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(90): Illuminate\\Database\\Migrations\\Migrator->run()
speedtest-tracker  | #20 /app/www/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
speedtest-tracker  | #21 /app/www/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
speedtest-tracker  | #22 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
speedtest-tracker  | #23 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
speedtest-tracker  | #24 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
speedtest-tracker  | #25 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
speedtest-tracker  | #26 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
speedtest-tracker  | #27 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
speedtest-tracker  | #28 /app/www/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
speedtest-tracker  | #29 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
speedtest-tracker  | #30 /app/www/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
speedtest-tracker  | #31 /app/www/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
speedtest-tracker  | #32 /app/www/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
speedtest-tracker  | #33 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
speedtest-tracker  | #34 /app/www/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
speedtest-tracker  | #35 {main}
```

**Comment by alexjustesen** [comment]
@thespad did `0.16.2` build? I missed updating the UI but the tagged version should fix this. Let me know if that's not the case.

**Comment by thespad** [comment]
It has built, it hadn't when I pulled it, I saw the build notifcation for 0.16.1 and didn't realise there was a followup.

All working now 👍🏻
