### ISSUE TITLE
Issue after Updating to 16.6

### ISSUE THREAD

**Issue by KrisTheCrazie** [alexjustesen/speedtest-tracker#1216]
**Describe the bug**
Stops with a fatal error

**To Reproduce**
Update from v16 to v16.6

**Expected behavior**
Should Start

**Environment (please complete the following information):**
- Docker Container on ubuntu
- 

**Logs**
```
[2024-02-22 08:14:16] production.ERROR: Could not create setting general.prune_results_older_than because it already exists {"exception":"[object] (Spatie\\LaravelSettings\\Exceptions\\SettingAlreadyExists(code: 0): Could not create setting general.prune_results_older_than because it already exists at /var/www/html/vendor/spatie/laravel-settings/src/Exceptions/SettingAlreadyExists.php:11)

[stacktrace]
#0 /var/www/html/vendor/spatie/laravel-settings/src/Migrations/SettingsMigrator.php(54): Spatie\\LaravelSettings\\Exceptions\\SettingAlreadyExists::whenAdding()
#1 /var/www/html/database/settings/2024_02_18_010000_add_prune_results_to_general_settings.php(9): Spatie\\LaravelSettings\\Migrations\\SettingsMigrator->add()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(493): Spatie\\LaravelSettings\\Migrations\\SettingsMigration@anonymous->up()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(410): Illuminate\\Database\\Migrations\\Migrator->runMethod()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(419): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->runMigration()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(37): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(756): Illuminate\\Console\\View\\Components\\Task->render()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(216): Illuminate\\Database\\Migrations\\Migrator->write()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(181): Illuminate\\Database\\Migrations\\Migrator->runUp()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(124): Illuminate\\Database\\Migrations\\Migrator->runPending()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(90): Illuminate\\Database\\Migrations\\Migrator->run()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#20 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#22 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#23 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#24 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#26 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}
"} 
In SettingAlreadyExists.php line 11:
                                                                               
  Could not create setting general.prune_results_older_than because it alread  
  y exists                                                                     
                                                                               
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
```

**Comment by alexjustesen** [comment]
IF you're comfortable editing database records go into the `settings` table and find that row and remote it. Then restart the container and it should successful finish the migrations.

**Comment by KrisTheCrazie** [comment]
I modified the table as suggested, restarted and it finished the migrations and is working now
