### ISSUE TITLE
Error exporting CSV / exporting results - 0 rows exported. 1,510 rows failed to export

### ISSUE THREAD

**Issue by rursache** [alexjustesen/speedtest-tracker#1376]
**Describe the bug**
```
Export completed
1 minute ago
Your result export has completed and 0 rows exported. 1,510 rows failed to export.
```

**To Reproduce**
1. Go to 'Results' (`/admin/results`)
2. Click on 'Export Results'
3. Doesn't matter what i check or uncheck
4. Press `Export`
5. Receive the confirmation notification then the error in notification popup

**Expected behavior**
Be able to export the logs

**Environment (please complete the following information):**
- OS: Ubuntu 23.10 x86_64
- Host: NUC11TNHi5 M11924-405
- Kernel: 6.7.9-060709-genericins
- CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz
- GPU: Intel TigerLake-LP GT2 [Iris Xe Graphic
- Memory: 29080MiB / 63962MiB
-  Architecture: amd64
 - Browser chrome but doesn't matter
 - Version 0.18.6

**Screenshots**
![screenshot](https://i.imgur.com/H1YRee6.png)

**Logs**
```
2024-04-12T22:01:05.028660679Z #19 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()
2024-04-12T22:01:05.028663957Z #20 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
2024-04-12T22:01:05.028667660Z #21 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2024-04-12T22:01:05.028676803Z #22 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
2024-04-12T22:01:05.028681100Z #23 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
2024-04-12T22:01:05.028685396Z #24 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
2024-04-12T22:01:05.028689640Z #25 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
2024-04-12T22:01:05.028692723Z #26 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
2024-04-12T22:01:05.028695529Z #27 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
2024-04-12T22:01:05.028697982Z #28 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon()
2024-04-12T22:01:05.028700366Z #29 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
2024-04-12T22:01:05.028702885Z #30 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
2024-04-12T22:01:05.028705344Z #31 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
2024-04-12T22:01:05.028707925Z #32 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
2024-04-12T22:01:05.028710316Z #33 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
2024-04-12T22:01:05.028712726Z #34 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
2024-04-12T22:01:05.028715142Z #35 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
2024-04-12T22:01:05.028717634Z #36 /app/www/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
2024-04-12T22:01:05.028720055Z #37 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
2024-04-12T22:01:05.028722565Z #38 /app/www/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
2024-04-12T22:01:05.028725483Z #39 /app/www/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
2024-04-12T22:01:05.028729640Z #40 /app/www/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
2024-04-12T22:01:05.028733294Z #41 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
2024-04-12T22:01:05.028741881Z #42 /app/www/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
2024-04-12T22:01:05.028746674Z #43 {main}
2024-04-12T22:01:05.028750742Z "} 
```

**Additional context**
Installed using docker:
```sh
docker run -d \
  --name speedtest-tracker \
  --restart unless-stopped \
  -p 48783:80 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Bucharest \
  -e DB_CONNECTION=pgsql \
  -e APP_KEY=DOESNTMATTER \
  -e DB_HOST=192.168.31.100 \
  -e DB_PORT=2211 \
  -e DB_DATABASE=speedtesttracker \
  -e DB_USERNAME=DOESNTMATTER \
  -e DB_PASSWORD=DOESNTMATTER \
  -v /home/radu/.speedtest-tracker:/config \
  lscr.io/linuxserver/speedtest-tracker:latest
```

I managed to export the data from InfluxDB however i wasted some time with this before. 
Please help me with a fix. Thanks!

**Comment by alexjustesen** [comment]
My guess is it isn't the job failing but somewhere in the export function. Can you turn debugging on, restart your container, export again and drop logs in a comment?

**Comment by tweek11** [comment]
I had the exact same issue the other day. Even switched over to the new image: lscr.io/linuxserver/speedtest-tracker:latest at the time and it did the same thing afterwards. 

However after version 0.19.0 was pushed 15 hours ago, it appears to have resolved the issue for me and is working again.

**Comment by rursache** [comment]
indeed `0.19.0` fixed the issue, i can export CSVs now. thanks!
