### ISSUE TITLE
[v0.3.0] Failed Jobs: one for every completed test

### ISSUE THREAD

**Issue by alexdelprete** [alexjustesen/speedtest-tracker#144]
**Describe the bug**
I enabled debug, and after almost one day, I noticed I had 17 failed jobs in the Jobs section (screenshot below). You can find the detailed log of the error for each failed job in the Logs section below. The error is the same for each failed job.

I checked the timing of those jobs and they were identical to the ones of the 17 results of completed tests. So I guess they didn't really fail, but I'm not sure about that.

**To Reproduce**
Enable debug and check the Failed Jobs list. You should find one for every completed test.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [Docker on Ubuntu]
-  Architecture: [amd64]
 - Browser [Edge]
 - Version [v0.3.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/7027842/201429349-14c988e6-f0c9-42d6-9bea-f7fe69479281.png)

**Logs**
From the **View Failed Job** window.

**Exception**:

```log
TypeError: Cannot access offset of type string on string in /var/www/html/app/Models/Result.php:69
Stack trace:
#0 /var/www/html/app/Jobs/SendDataToInfluxDbV2.php(63): App\Models\Result->formatForInfluxDB2()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\SendDataToInfluxDbV2->handle()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\Queue\Jobs\Job->fire()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\Queue\Worker->process()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker->runJob()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\Queue\Worker->daemon()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\Queue\Console\WorkCommand->runWorker()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Illuminate\Container\Container->call()
#27 /var/www/html/vendor/symfony/console/Command/Command.php(308): Illuminate\Console\Command->execute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(148): Symfony\Component\Console\Command\Command->run()
#29 /var/www/html/vendor/symfony/console/Application.php(1014): Illuminate\Console\Command->run()
#30 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#31 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(111): Symfony\Component\Console\Application->run()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run()
#34 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#35 {main}
```

**Payload**:

```json
{
  "uuid": "72551a41-a804-4eea-b767-1e2f0754aa36",
  "displayName": "App\\Jobs\\SendDataToInfluxDbV2",
  "job": "Illuminate\\Queue\\CallQueuedHandler@call",
  "maxTries": null,
  "maxExceptions": null,
  "failOnTimeout": false,
  "backoff": null,
  "timeout": null,
  "retryUntil": null,
  "data": {
    "commandName": "App\\Jobs\\SendDataToInfluxDbV2",
    "command": "O:29:\"App\\Jobs\\SendDataToInfluxDbV2\":2:{s:6:\"result\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":5:{s:5:\"class\";s:17:\"App\\Models\\Result\";s:2:\"id\";i:359;s:9:\"relations\";a:0:{}s:10:\"connection\";s:5:\"mysql\";s:15:\"collectionClass\";N;}s:8:\"settings\";O:29:\"App\\Settings\\InfluxDbSettings\":5:{s:10:\"v2_enabled\";b:1;s:6:\"v2_url\";s:30:\"http://influxdb2.axel.dom:8086\";s:6:\"v2_org\";s:11:\"domain.net\";s:9:\"v2_bucket\";s:17:\"speedtest-tracker\";s:8:\"v2_token\";s:88:\"yu0H-YQ11111111111_REDACTED_22222222222222222222222222233333333333333==\";}}"
  }
}
```

**Comment by alexjustesen** [comment]
@alexdelprete or @future10se the branch attached to #144 should resolve the InfluxDb issue. Would either of you mind pulling and testing?

Also found that apparently `packetLoss` doesn't always get returned from the CLI so that field is now optional in the returned data.

**Comment by alexdelprete** [comment]
> Would either of you mind pulling and testing?

so for docker, I can use the branch name as the image tag to pull it? didn't know that, I'll try it.

**Comment by alexjustesen** [comment]
You'll want to pull the branch, then build the image manually `docker build . -t some-image-name` and then start that container. 

I don't have access to my home lab for a few more days so I can't really test the influxdb job. All I can test is that the formatter no longer fails.

**Comment by alexdelprete** [comment]
I used VSCode to edit directly the file in the container, then restarted it.

The fix is working fine, no item in the Failed Jobs list, and I have data in Influx. :)

**Comment by alexjustesen** [comment]
Cool, because I merged it on accident haha

**Comment by alexdelprete** [comment]
> Cool, because I merged it on accident haha

that's why I tested it right away...I had guests but I took 10m off to test because you merged it and I wanted to be sure. :)

**Comment by future10se** [comment]
Hi @alexjustesen, sorry for the late reply, timezones 😅 

Yes, I can confirm on my end that InfluxDB integration is working again. Thank you!
