### ISSUE TITLE
Error thrown when running app:reset-user-password command

### ISSUE THREAD

**Issue by ThomasHFWright** [alexjustesen/speedtest-tracker#1455]
**Describe the bug**
I'm unable to reset my user's password as an error is thrown when running the app:reset-user-password command

**To Reproduce**
1. Go to container CLI
2. Run command `php artisan app:reset-user-password myemail@gmail.com`
3. See error `Object of class App\Console\Commands\ResetUserPassword could not be converted to string`

**Expected behavior**
Should reset password of specified user and return new password

**Environment (please complete the following information):**
 - OS: Synology NAS DiskStation Manager 7.2-64570
-  Architecture: amd64 (Synology ds918+)
 - Docker: Synology Container Manager 20.10.23-1437
 - Version: linuxserver/speedtest-tracker:latest (0.19.0)

**Logs**
```
root@linuxserver-speedtest-tracker-1:/app/www# php artisan app:reset-user-password myemail@gmail.com -vvv
[2024-05-31 12:05:12] production.ERROR: Object of class App\Console\Commands\ResetUserPassword could not be converted
to string {"exception":"[object] (Error(code: 0): Object of class App\\Console\\Commands\\ResetUserPassword could not be
converted to string at /app/www/app/Console/Commands/ResetUserPassword.php:35)
[stacktrace]
#0 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\ResetUserPassword->handle()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#6 /app/www/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#7 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#8 /app/www/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#9 /app/www/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#10 /app/www/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#11 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#12 /app/www/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#13 {main}
"}

In ResetUserPassword.php line 35:

  [Error]
  Object of class App\Console\Commands\ResetUserPassword could not be converted to string


Exception trace:
  at /app/www/app/Console/Commands/ResetUserPassword.php:35
 App\Console\Commands\ResetUserPassword->handle() at /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php:41
 Illuminate\Container\Util::unwrapIfClosure() at /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
 Illuminate\Container\BoundMethod::call() at /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:662
 Illuminate\Container\Container->call() at /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php:211
 Illuminate\Console\Command->execute() at /app/www/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->run() at /app/www/vendor/symfony/console/Application.php:1096
 Symfony\Component\Console\Application->doRunCommand() at /app/www/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /app/www/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:201
 Illuminate\Foundation\Console\Kernel->handle() at /app/www/artisan:35
```

**Additional context**
Looks like this person has the same issue in their post https://github.com/alexjustesen/speedtest-tracker/discussions/695#discussioncomment-8827182

**Comment by alexjustesen** [comment]
Try wrapping the email address in quotes, `"address@example.com"`, haven't seen that issue yet.

**Comment by ThomasHFWright** [comment]
I get the same error when wrapping my email in quotes, but a different error when specifying the email parameter directly:

```
root@linuxserver-speedtest-tracker-1:/app/www# php artisan app:reset-user-password --email=address@example.com -vvv 
[2024-06-04 08:11:22] production.ERROR: The "--email" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--email\" option does not exist. at /app/www/vendor/symfony/console/Input/ArgvInput.php:223)
[stacktrace] 
#0 /app/www/vendor/symfony/console/Input/ArgvInput.php(150): Symfony\\Component\\Console\\Input\\ArgvInput->addLongOption() 
#1 /app/www/vendor/symfony/console/Input/ArgvInput.php(85): Symfony\\Component\\Console\\Input\\ArgvInput->parseLongOption()
#2 /app/www/vendor/symfony/console/Input/ArgvInput.php(74): Symfony\\Component\\Console\\Input\\ArgvInput->parseToken() 
#3 /app/www/vendor/symfony/console/Input/Input.php(56): Symfony\\Component\\Console\\Input\\ArgvInput->parse()
#4 /app/www/vendor/symfony/console/Command/Command.php(285): Symfony\\Component\\Console\\Input\\Input->bind()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#6 /app/www/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run() 
#7 /app/www/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand() 
#8 /app/www/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#9 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run() 
#10 /app/www/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#11 {main} 
"} 
 
The "--email" option does not exist. 
 
 
Exception trace: 
In ArgvInput.php line 223: 

[Symfony\Component\Console\Exception\RuntimeException] 
at /app/www/vendor/symfony/console/Input/ArgvInput.php:223 
 Symfony\Component\Console\Input\ArgvInput->addLongOption() at /app/www/vendor/symfony/console/Input/ArgvInput.php:150
 Symfony\Component\Console\Input\ArgvInput->parseLongOption() at /app/www/vendor/symfony/console/Input/ArgvInput.php:85 
 Symfony\Component\Console\Input\ArgvInput->parseToken() at /app/www/vendor/symfony/console/Input/ArgvInput.php:74
 Symfony\Component\Console\Input\ArgvInput->parse() at /app/www/vendor/symfony/console/Input/Input.php:56 
 Symfony\Component\Console\Input\Input->bind() at /app/www/vendor/symfony/console/Command/Command.php:285 
 Symfony\Component\Console\Command\Command->run() at /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php:180 
 Illuminate\Console\Command->run() at /app/www/vendor/symfony/console/Application.php:1096
 Symfony\Component\Console\Application->doRunCommand() at /app/www/vendor/symfony/console/Application.php:324 
 Symfony\Component\Console\Application->doRun() at /app/www/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:201 
 Illuminate\Foundation\Console\Kernel->handle() at /app/www/artisan:35
```

**Comment by alexjustesen** [comment]
Thanks, I'll dig into it
