### ISSUE TITLE
500

### ISSUE THREAD

**Issue by rbhalla** [alexjustesen/speedtest-tracker#1523]
**Describe the bug**
Apologies, but this is another 500 bug.

**To Reproduce**
1. Setup using unraid
2. Launch UI

Unfortunately I don't have a neat docker compose file, you do it through the UI

<img width="1607" alt="Screenshot 2024-06-12 at 00 34 30" src="https://github.com/alexjustesen/speedtest-tracker/assets/5897045/81898fc4-68e1-4e2a-98d2-1dc536bad1eb">

<img width="1607" alt="Screenshot 2024-06-12 at 00 34 42" src="https://github.com/alexjustesen/speedtest-tracker/assets/5897045/391b5d85-6b97-4feb-9d2d-fca4e3a3db82">

This is the command that's run:
```
docker run
  -d
  --name='speedtest-tracker'
  --net='bridge'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="server"
  -e HOST_CONTAINERNAME="speedtest-tracker"
  -e 'APP_KEY'='base64:C9JQOup4ua6+beUaYKzzYI04iG5yL+qS9TvuJN2vqQM='
  -e 'DB_CONNECTION'='sqlite'
  -e 'SPEEDTEST_SCHEDULE'='* */6 * * *'
  -e 'SPEEDTEST_SERVERS'='54746,43730,57318,59923,63030,40377,31171,23389,34881,32950,47230,55137,30690,34948,40788,6032,12920,31183,33216'
  -e 'DB_HOST'=''
  -e 'DB_PORT'=''
  -e 'DB_DATABASE'=''
  -e 'DB_USERNAME'=''
  -e 'DB_PASSWORD'=''
  -e 'DISPLAY_TIMEZONE'='Etc/UTC'
  -e 'PRUNE_RESULTS_OLDER_THAN'='0'
  -e 'APP_DEBUG'='true'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:80]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/speedtest-tracker-logo.png'
  -p '8765:80/tcp'
  -v '/mnt/user/appdata/speedtest-tracker':'/config':'rw' 'lscr.io/linuxserver/speedtest-tracker'
8cceab1f92a1758063e038b021dcfe1a0369b681ab2d3c7fef2861e56a55418d
```

**Expected behavior**
Expect it to load.

**Environment (please complete the following information):**
 - OS: Unraid 6.12.8
-  Architecture: x86_64
 - Browser: chrome
 - Version latest (as of 12th June)

**Screenshots**
Config above.

<img width="540" alt="Screenshot 2024-06-12 at 00 39 53" src="https://github.com/alexjustesen/speedtest-tracker/assets/5897045/b08fdbc6-e5f8-4ee5-a05f-969f9f5f2853">

Problem: 
What is particularly strange is, I am getting no logs and setting `APP_DEBUG=true` doesn't seem to show any extra logs, or the appropriate error screen when loading the UI.

**Logs**

Nothing more than this:
<img width="1202" alt="Screenshot 2024-06-12 at 00 41 05" src="https://github.com/alexjustesen/speedtest-tracker/assets/5897045/61021165-6db5-4cc9-9847-142cf515a6a8">

**Additional context**
It is not https://github.com/alexjustesen/speedtest-tracker/issues/500 since I have waited 15 minutes and nothing.
I saw in https://github.com/alexjustesen/speedtest-tracker/issues/1505 the `APP_KEY` was malformed, I have checked that's not the case here.

The machine is a 4 core i7 with 16gb ram, so I don't think it's a power issue.

**Comment by alexjustesen** [comment]
Try droppin `-e 'DISPLAY_TIMEZONE'='Etc/UTC'` as `UTC` is the expected value and the default.

**Comment by rbhalla** [comment]
I appreciate the quick response here @alexjustesen, thank you!

Unfortunately I tried that and still have the same issue. Logs don't seem to have any verbose output and still getting a 500.

Are there any other ways I can debug? Happy to attach to the container and troubleshoot there if any log files may help more.

**Comment by svenvg93** [comment]
Can you enable debug by adding APP_DEBUG=true to the environment variables. Restart the container. Maybe it will show something more then.

If you have debug enable make sure you're viewing the console of the container for the log or checkout /app/www/storage/logs/laravel.log for additional outputs when attached to the container.

**Comment by BenGeba** [comment]
Hi, 

I have the same problem and nothing was displayed in the "normal" logs. However, I was able to find something under /app/www/storage/logs/laravel.log. These two errors occur:

```
[2024-06-14 08:05:21] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (Error(code: 0): Class \"Illuminate\\Support\\Collection\" not found at /config/www/vendor/laravel/framework/src/Illuminate/Collections/helpers.php:15)
[stacktrace]
#0 /config/www/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(244): collect()
#1 /config/www/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(202): Illuminate\\Log\\LogManager->createStackDriver()
#2 /config/www/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(118): Illuminate\\Log\\LogManager->resolve()
#3 /config/www/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(98): Illuminate\\Log\\LogManager->get()
#4 /config/www/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(551): Illuminate\\Log\\LogManager->driver()
#5 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(237): Illuminate\\Log\\LogManager->error()
#6 /config/www/app/Exceptions/Handler.php(39): Illuminate\\Foundation\\Exceptions\\Handler->report()
#7 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(88): App\\Exceptions\\Handler->report()
#8 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(130): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#9 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#10 {main}
"} 
[2024-06-14 08:05:21] laravel.ERROR: During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /config/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1411
Stack trace:
#0 /config/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(11): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /config/www/vendor/composer/ClassLoader.php(478): include('...')
#2 /config/www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 /config/www/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): Composer\Autoload\ClassLoader->loadClass()
#4 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()
#5 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation\PackageManifest->config()
#6 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#7 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#8 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\Foundation\Application->bootstrapWith()
#9 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\Foundation\Http\Kernel->bootstrap()
#10 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#11 /config/www/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle()
#12 {main} {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\\Support\\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /config/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1411
Stack trace:
#0 /config/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(11): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /config/www/vendor/composer/ClassLoader.php(478): include('...')
#2 /config/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()
#3 /config/www/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): Composer\\Autoload\\ClassLoader->loadClass()
#4 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()
#5 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\\Foundation\\PackageManifest->config()
#6 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\\Foundation\\PackageManifest->aliases()
#7 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterFacades->bootstrap()
#8 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith()
#9 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#10 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#11 /config/www/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle()
#12 {main} at /config/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:11)
[stacktrace]
```

**Comment by alexjustesen** [comment]
Let's remove a couple of things...

First remove `TZ` as this functionally does nothing:

```
-e TZ="Europe/London"
```

Second since you're using `sqlite` as your DB driver remove the additional `DB_` environment variables:

```
-e 'DB_HOST'=''
-e 'DB_PORT'=''
-e 'DB_DATABASE'=''
-e 'DB_USERNAME'=''
-e 'DB_PASSWORD'=''
```

**Comment by Gex2501** [comment]
> Let's remove a couple of things...
> 
> First remove `TZ` as this functionally does nothing:
> 
> ```
> -e TZ="Europe/London"
> ```
> 
> Second since you're using `sqlite` as your DB driver remove the additional `DB_` environment variables:
> 
> ```
> -e 'DB_HOST'=''
> -e 'DB_PORT'=''
> -e 'DB_DATABASE'=''
> -e 'DB_USERNAME'=''
> -e 'DB_PASSWORD'=''
> ```

I did those things, even installed a fresh container, turned on DEBUG, this is what I'm getting regardless of those variables being set.

![Capture](https://github.com/alexjustesen/speedtest-tracker/assets/63863/c38f5b96-e62d-4b0e-afd6-e74aee98df4c)

**Comment by Gex2501** [comment]
Also, if I go back to version 0.19.0 with the repository taged: lscr.io/linuxserver/speedtest-tracker:0.19.0 then it works again.

**Comment by Gex2501** [comment]
I think I got it working. I previously had no APP_KEY set. After going back to 0.19.0 I set the APP_KEY, there was another error at first but then things worked. I went back to set no tag on the repository and it's good now. I wonder if deleting the old /config/keys would have fixed it...

**Comment by rbhalla** [comment]
I was able to remove 

```
-e 'DB_HOST'=''
-e 'DB_PORT'=''
-e 'DB_DATABASE'=''
-e 'DB_USERNAME'=''
-e 'DB_PASSWORD'=''
```

but `-e TZ="Europe/London"` is added by unraid, not something I can control unfortunately.

My `laravel.log` file is completely empty (0 bytes) and going back to 0.19.0 did nothing for me.

I'd still consider this issue unresolved so would prefer to keep it open to see if anyone else has any ideas.

Do you know where else I may be able to find logs?

**Comment by rbhalla** [comment]
On that last note, I started looking at other logs I could find, I found this in `config/log/nginx/error.log`:

```
2024/06/16 00:09:58 [error] 362#362: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /config/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1411
Stack trace:
#0 /config/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(11): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /config/www/vendor/composer/ClassLoader.php(478): include('...')
#2 /config/www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 /config/www/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): Composer\Autoload\ClassLoader->loadClass()
#4 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()
#5 /config/www/vendor/laravel/framework/src/Illumin...; PHP message: PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of Symfony\Component\Finder\Iterator\SortableIterator::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /config/www/vendor/symfony/finder/Iterator/SortableIterator.php:85
Stack trace:
#0 /config/www/vendor/symfony/finder/Iterator/SortableIterator.php(19): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /config/www/vendor/composer/ClassLoader.php(478): include('...')
#2 /config/www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 /config/www/vendor/symfony/finder/Finder.php(438): Composer\Autoload\ClassLoader->loadClass()
#4 /config/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(544): Symfony\Component\Finder\Finder->sortByName()
#5 /config/ww
```

That's not me cutting off the end, it cuts off itself.

**Comment by svenvg93** [comment]
@rbhalla I can try to help you out, I don't have unraid myself to test it. 
When using your docker run without the `HOST_` and `net_unraid` stuff the App works as intended.
Can you try to run the docker run on the command line to see if that works.
