### ISSUE TITLE
Column not found: 1054 Unknown column 'server_id' in 'field list'

### ISSUE THREAD

**Issue by kimpenhaus** [alexjustesen/speedtest-tracker#1554]
**Describe the bug**
when checking the docker logs recently I stumbled upon this error (which is in the logs quite frequently). I can't tell since which version-update I am facing this - as the app itself seems to run with no issues. So I wonder if I am the only one who might see this issue - I am using watchtower to auto-update the docker image... maybe some incompatibilites were introduced with that...

**To Reproduce**
1. checking docker logs

**Expected behavior**
no issue 🙂 

**Environment (please complete the following information):**
 - OS: docker image `lscr.io/linuxserver/speedtest-tracker:latest`
 - Version 0.20.6

**Screenshots**

**Logs**
```
[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'server_id' in 'field list' at /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:592)
[stacktrace]
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(592): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(800): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(767): Illuminate\\Database\\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(584): Illuminate\\Database\\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(536): Illuminate\\Database\\Connection->affectingStatement()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3722): Illuminate\\Database\\Connection->update()
#6 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1104): Illuminate\\Database\\Query\\Builder->update()
#7 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1218): Illuminate\\Database\\Eloquent\\Builder->update()
#8 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1135): Illuminate\\Database\\Eloquent\\Model->performUpdate()
#9 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(995): Illuminate\\Database\\Eloquent\\Model->save()
#10 /app/www/app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php(66): Illuminate\\Database\\Eloquent\\Model->update()
#11 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\Speedtests\\ExecuteOoklaSpeedtest->handle()
#12 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#16 /app/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#17 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#18 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /app/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#20 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#21 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#22 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Pipeline\\Pipeline->then()
#24 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#25 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
#26 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#27 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
#28 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
#29 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(139): Illuminate\\Queue\\Worker->daemon()
#30 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(122): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#31 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#32 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#33 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#34 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#35 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#36 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#37 /app/www/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#38 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#39 /app/www/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#40 /app/www/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#41 /app/www/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#42 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\\Component\\Console\\Application->run()
#43 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1198): Illuminate\\Foundation\\Console\\Kernel->handle()
#44 /app/www/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#45 {main}
```

**Additional context**

I not pretty sure what else I can provide - if you need more information just let mne known 🙁 

thanks,
marcus

**Comment by svenvg93** [comment]
Looking at the error is seems the `sever_id` is not in the database. 
Do you see the server id in the results table (you might need to turn the colunm on)?

Can you try the following

1. Go to container CLI
2. Make sure your in /app/www
3. Run command: php artisan migrate --force

**Comment by kimpenhaus** [comment]
@svenvg93 thanks for your feedback - I just double checked from phpmyadmin and it looks like it is not in the table:

<img width="400" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/575109/129459b2-6547-4163-98c6-693955fa7fa5">

trying to force migrations doesn't seem to have any effect:

<img width="400" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/575109/58ebcc48-ab49-4ac5-b859-00325b944e04">

this is what my migrations look like:

<img width="600" alt="image" src="https://github.com/alexjustesen/speedtest-tracker/assets/575109/bbfcacd1-4808-46b6-9409-278589fd72b7">

thakns for jumping in and trying to help 🙏🏼

**Comment by kimpenhaus** [comment]
just guessing if the issue was introduced with PR #1327 - prior installation should have been migrated as the create table was already executed...

Im thinking about dropping and recreating the database - might be the easiest way...

**Comment by svenvg93** [comment]
> Im thinking about dropping and recreating the database - might be the easiest way...

Then you can also do `php artisan migrate:clean --force`. It will reset everything.

**Comment by kimpenhaus** [comment]
looks better now - thanks :)

**Comment by svenvg93** [comment]
Great! Happy to help!
