### ISSUE TITLE
[BUG] SpeedTest-tracker stop working from time to time

### ISSUE THREAD

**Issue by chatainsim** [alexjustesen/speedtest-tracker#1613]
**Describe the bug**
Just let Speedtest-tracker do his job and from time to time it stop working.
I had to restart the container every time

**Environment (please complete the following information):**
 - OS: Debian 12 Bookworm
-  Architecture: amd64
- Docker: 27.0.3
 - Version  0.20.7

**Logs**
```
[2024-07-18 14:33:34] production.ERROR: SQLSTATE[HY000]: General error: 1 no such column: server_id (Connection: sqlite, SQL: update "results" set "data" = {"type":"log","timestamp":"2024-07-18T12:33:34Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}, "status" = failed, "server_id" = ?, "updated_at" = 2024-07-18 14:33:34 where "id" = 1708) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1 no such column: server_id (Connection: sqlite, SQL: update \"results\" set \"data\" = {\"type\":\"log\",\"timestamp\":\"2024-07-18T12:33:34Z\",\"message\":\"Configuration - Could not retrieve or read configuration (ConfigurationError)\",\"level\":\"error\"}, \"status\" = failed, \"server_id\" = ?, \"updated_at\" = 2024-07-18 14:33:34 where \"id\" = 1708) at /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:813)
[stacktrace]
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(767): Illuminate\\Database\\Connection->runQueryCallback()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(584): Illuminate\\Database\\Connection->run()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(536): Illuminate\\Database\\Connection->affectingStatement()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3722): Illuminate\\Database\\Connection->update()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1104): Illuminate\\Database\\Query\\Builder->update()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1218): Illuminate\\Database\\Eloquent\\Builder->update()
#6 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1135): Illuminate\\Database\\Eloquent\\Model->performUpdate()
#7 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(995): Illuminate\\Database\\Eloquent\\Model->save()
#8 /app/www/app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php(66): Illuminate\\Database\\Eloquent\\Model->update()
#9 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\Speedtests\\ExecuteOoklaSpeedtest->handle()
#10 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#14 /app/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#15 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#16 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /app/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#18 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#19 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#20 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Pipeline\\Pipeline->then()
#22 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#23 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
#24 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#25 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
#26 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
#27 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(139): Illuminate\\Queue\\Worker->daemon()
#28 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(122): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#29 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#30 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#31 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#32 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#33 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#34 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#35 /app/www/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#36 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#37 /app/www/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#38 /app/www/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#39 /app/www/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#40 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\\Component\\Console\\Application->run()
#41 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1198): Illuminate\\Foundation\\Console\\Kernel->handle()
#42 /app/www/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#43 {main}

[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such column: server_id at /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:592)
[stacktrace]
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(592): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(800): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(767): Illuminate\\Database\\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(584): Illuminate\\Database\\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(536): Illuminate\\Database\\Connection->affectingStatement()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3722): Illuminate\\Database\\Connection->update()
#6 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1104): Illuminate\\Database\\Query\\Builder->update()
#7 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1218): Illuminate\\Database\\Eloquent\\Builder->update()
#8 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1135): Illuminate\\Database\\Eloquent\\Model->performUpdate()
#9 /app/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(995): Illuminate\\Database\\Eloquent\\Model->save()
#10 /app/www/app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php(66): Illuminate\\Database\\Eloquent\\Model->update()
#11 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\Speedtests\\ExecuteOoklaSpeedtest->handle()
#12 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#16 /app/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#17 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#18 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /app/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#20 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#21 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#22 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Pipeline\\Pipeline->then()
#24 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#25 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
#26 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#27 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
#28 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
#29 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(139): Illuminate\\Queue\\Worker->daemon()
#30 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(122): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#31 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#32 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#33 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#34 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#35 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#36 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#37 /app/www/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#38 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#39 /app/www/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#40 /app/www/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#41 /app/www/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#42 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\\Component\\Console\\Application->run()
#43 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1198): Illuminate\\Foundation\\Console\\Kernel->handle()
#44 /app/www/artisan(13): Illuminate\\Foundation\\Application->handleCommand()
#45 {main}
"} 
```
Thanks

**Comment by alexjustesen** [comment]
In the error message looks like the server it's trying to reach is not available:

```
Configuration - Could not retrieve or read configuration (ConfigurationError)
```

Check you list of servers and also your internet connection as this error is thrown by the CLI when it can't connect to a specified server. Separately I'll check into why the DB write is failing.

**Comment by chatainsim** [comment]
I haven't specified any server in the docker file.
VM still has internet access.

**Comment by alexjustesen** [comment]
It can happen from time to time on Ookla server's, it's tough to narrow down the reason which is why a most people specify a list of servers.
