### ISSUE TITLE
Button "Test mail channel" shows error 500 page 

### ISSUE THREAD

**Issue by mzeecedric** [alexjustesen/speedtest-tracker#176]
**Describe the bug**
When I click on the button  "Test mail channel" an error page opens in a lightbox.

**To Reproduce**
1. Go to the /admin Dashboard, then Notifications and enable the Mail Notifications. (I have also enabled "Notify on threshold failures" there)
2. Click on "Test mail channel"
3. Lightbox with Error 500 opens

**Expected behavior**
Show information whether an email was sent or the mail could not be sent.

**Environment (please complete the following information):**
Running the "latest" version (I am even unable to say what exact version I'm running, see #132) with Docker on Ubuntu 22.04, x86-64.

In case there is a connection to the setup in my .env file... I am using gmail. What I was unable to find in the docs is how to configure MAIL_ENCRYPTION" so setting this to "TLS" is my guess. 

```
MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=mail@example.com
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDRESS="mail@example.com"
MAIL_FROM_NAME="${APP_NAME}"
```

**Logs**
```
[2022-11-25 14:37:34] production.ERROR: Attempt to read property "email" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"email\" on null at /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:688)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(688): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(580): Illuminate\\Mail\\Mailable->setAddress()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(158): Illuminate\\Mail\\Mailable->to()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(124): Illuminate\\Mail\\PendingMail->fill()
#5 /var/www/html/app/Filament/Pages/Settings/NotificationPage.php(157): Illuminate\\Mail\\PendingMail->send()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Filament\\Pages\\Settings\\NotificationPage->sendTestMailNotification()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\\Container\\BoundMethod::call()
#11 /var/www/html/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(38): Livewire\\Component->callMethod()
#12 /var/www/html/vendor/livewire/livewire/src/LifecycleManager.php(89): Livewire\\HydrationMiddleware\\PerformActionCalls::hydrate()
#13 /var/www/html/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\\LifecycleManager->hydrate()
#14 /var/www/html/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(20): Livewire\\Connection\\ConnectionHandler->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\\Routing\\Route->run()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(728): Illuminate\\Pipeline\\Pipeline->then()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\\Routing\\Router->runRouteWithinStack()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRoute()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->dispatchToRoute()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#40 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#57 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#58 {main}
"} 
```

**Additional context**

Anyhow I receive the testmail sent and also other notifications via mail arrive.

**Comment by alexjustesen** [comment]
@mzeecedric for Gmail I know you need to create an app password, did you do that as well? I also think I've used port 465 for Gmail in the past.

**Comment by mzeecedric** [comment]
Yes, I'm using an app password and emails are working as I wrote at the bottom. Just the error instead of any readable output in the gui

**Comment by mzeecedric** [comment]
I receive three notifications via the alert-icon and also three mails instead of a single notification, is this a known issue?

**Comment by alexjustesen** [comment]
3 mails occurred because the worker will try a job in the queue 3 times before marking it as "failed".  I'm online for as long as my daughter let's me get away with it this morning and hopefully can look into this.

Also FYI, I use Mailgun for all my homelab emails. They have a free tier for 1000 emails a month so might be worth checking that out too.

**Comment by alexjustesen** [comment]
Just gave this a test and was able to send mail with my gmail account with the env below, double checking but did you add recipients?

```env
MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME="*****@gmail.com"
MAIL_PASSWORD="******************"
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS="*****@gmail.com"
MAIL_FROM_NAME="${APP_NAME}"
```

**Comment by alexdelprete** [comment]
> Also FYI, I use Mailgun for all my homelab emails

I use [msmtpd](https://github.com/crazy-max/docker-msmtpd) as my homelab's smtp forwarder, so I'm able to change the cloud smtp provider easily, right now I'm using Google, but I can switch without reconfiguring any homelab service.

I'll check mailgun, thanks for the tip.

**Comment by mzeecedric** [comment]
@alexjustesen I do not have an issue with emails, I am receiving email-notifications. Its just this error that I see as soon as I use the "Test mail channel" button:

![Bildschirmfoto 2022-11-27 um 00 11 52](https://user-images.githubusercontent.com/1816071/204112203-60748518-b210-4be7-9330-d5ab8e829860.png)

This is what I see:

![Bildschirmfoto 2022-11-27 um 00 07 55](https://user-images.githubusercontent.com/1816071/204112192-5557cf9a-8cb0-4d03-8307-765417366b99.png)

I receive mails...
![Bildschirmfoto 2022-11-27 um 00 08 23](https://user-images.githubusercontent.com/1816071/204112198-684a7aa5-81dd-48d4-be1e-ea1090f1f5d7.png)

**Comment by alexjustesen** [comment]
That's interesting, can you go into the `.env` file in the mounted location and change `APP_DEBUG` to `true`? This way it'll show you the output of the system error.

**Comment by mzeecedric** [comment]
@alexjustesen I just figured out what the reason was... I had an empty recipients-field below that caused the error. I was wondering about the empty field, I also hit delete once, but I guess I did not hit save changes at the bottom. I also realize that the screenshot above is without that field. 

What might be a small improvement is to **prevent empty recipients** when hitting save. Thank you for your help! I'll close this...

**Comment by alexjustesen** [comment]
Do you mind opening a separate issue for that suggestion so I don't lose it in chat?

**Comment by alexdelprete** [comment]
> What might be a small improvement is to **prevent empty recipients** when hitting save. Thank you for your help! I'll close this...

@alexjustesen Isn't this already done in PR #177 ?

**Comment by alexjustesen** [comment]
> > What might be a small improvement is to **prevent empty recipients** when hitting save. Thank you for your help! I'll close this...
> 
> @alexjustesen Isn't this already done in PR #177 ?

For the most part yes but it's not validating correctly it looks like

**Comment by alexdelprete** [comment]
@mzeecedric Cedric, what version did you use for the test of the email?

> For the most part yes but it's not validating correctly it looks like

Was #177 merged in latest available version? Maybe he's testing with the previous version.

**Comment by mzeecedric** [comment]
@alexdelprete "Speedtest Tracker v0.4.2"
