### ISSUE TITLE
PostgreSQL application issues on brand new install

### ISSUE THREAD

**Issue by Kaaybi** [alexjustesen/speedtest-tracker#184]
**Describe the bug**
The application doesn't seem to work correctly with PostgresQL.

**To Reproduce**
1. Follow install instructions with Postresdb
2. Start container
3. Navigate to webserver
4. Login as admin@example.com
5. See error 500

**Expected behavior**
Be able to navigate into application.

**Environment (please complete the following information):**
 - OS: Debian
-  Architecture: amd64
 - Browser: Firefox
 - Version: 107.0 64bits
 - Db: Postgresdb v15.1 alpine
 - Speedtest-tracker v0.4.2

**Logs**
```
28/11/2022 21:32:22
[2022-11-28 20:32:22] production.ERROR: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text ->> unknown
28/11/2022 21:32:22
LINE 1: ...ifications"."notifiable_id" is not null and "data"->>'format...
28/11/2022 21:32:22
                                                             ^
28/11/2022 21:32:22
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select * from "notifications" where "notifications"."notifiable_type" = App\Models\User and "notifications"."notifiable_id" = 1 and "notifications"."notifiable_id" is not null and "data"->>'format' = filament order by "created_at" desc) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text -
28/11/2022 21:32:22
>> unknown
28/11/2022 21:32:22
LINE 1: ...ifications\".\"notifiable_id\" is not null and \"data\"->>'format...
28/11/2022 21:32:22
                                                             ^
28/11/2022 21:32:22
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select * from \"notifications\" where \"notifications\".\"notifiable_type\" = App\\Models\\User and \"notifications\".\"notifiable_id\" = 1 and \"notifications\".\"notifiable_id\" is not null and \"data\"->>'format' = filament order by \"created_at\" desc) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) (View: /var/www/html/vendor/filament/notifications/resources/views/components/database/index.blade.php) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
28/11/2022 21:32:22
[stacktrace]
28/11/2022 21:32:22
#0 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(106): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()
28/11/2022 21:32:22
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Livewire\\LivewireViewCompilerEngine->handleViewException()
28/11/2022 21:32:22
#2 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
28/11/2022 21:32:22
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Livewire\\LivewireViewCompilerEngine->evaluatePath()
28/11/2022 21:32:22
#4 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
28/11/2022 21:32:22
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(152): Livewire\\LivewireViewCompilerEngine->get()
28/11/2022 21:32:22
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\\View\\View->getContents()
28/11/2022 21:32:22
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(104): Illuminate\\View\\View->renderContents()
28/11/2022 21:32:22
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
28/11/2022 21:32:22
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
28/11/2022 21:32:22
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(835): Illuminate\\Http\\Response->__construct()
28/11/2022 21:32:22
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(804): Illuminate\\Routing\\Router::toResponse()
28/11/2022 21:32:22
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\\Routing\\Router->prepareResponse()
28/11/2022 21:32:22
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
28/11/2022 21:32:22
#14 /var/www/html/vendor/filament/filament/src/Http/Middleware/MirrorConfigToSubpackages.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Filament\\Http\\Middleware\\MirrorConfigToSubpackages->handle()
28/11/2022 21:32:22
#16 /var/www/html/vendor/filament/filament/src/Http/Middleware/DispatchServingFilamentEvent.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Filament\\Http\\Middleware\\DispatchServingFilamentEvent->handle()
28/11/2022 21:32:22
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
28/11/2022 21:32:22
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
28/11/2022 21:32:22
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
28/11/2022 21:32:22
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle()
28/11/2022 21:32:22
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
28/11/2022 21:32:22
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
28/11/2022 21:32:22
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
28/11/2022 21:32:22
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
28/11/2022 21:32:22
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
28/11/2022 21:32:22
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(728): Illuminate\\Pipeline\\Pipeline->then()
28/11/2022 21:32:22
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\\Routing\\Router->runRouteWithinStack()
28/11/2022 21:32:22
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRoute()
28/11/2022 21:32:22
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->dispatchToRoute()
28/11/2022 21:32:22
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
28/11/2022 21:32:22
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
28/11/2022 21:32:22
#42 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
28/11/2022 21:32:22
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
28/11/2022 21:32:22
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
28/11/2022 21:32:22
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
28/11/2022 21:32:22
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
28/11/2022 21:32:22
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
28/11/2022 21:32:22
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
28/11/2022 21:32:22
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
28/11/2022 21:32:22
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
28/11/2022 21:32:22
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
28/11/2022 21:32:22
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
28/11/2022 21:32:22
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
28/11/2022 21:32:22
#61 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
28/11/2022 21:32:22
#62 {main}
```

**Comment by alexjustesen** [comment]
Since you have a fresh install can you run `php artisan migrate:fresh --force`, if that works can you run `php artisan app:install --force`?

**Comment by Kaaybi** [comment]
I'm still getting the 500 error after login as admin@example.com on /admin, same errors appears in the logs (ERROR:  operator does not exist) after running those commands and restarting the container.

**Comment by alexjustesen** [comment]
Thanks I'll take a peak into it, give me a couple of days as I'm currently "out of the office".

**Comment by alexjustesen** [comment]
@Kaaybi the next release will have a fix for this, once that release is published run `php artisan app:install --force` from within the container and you should be all set.
