### ISSUE TITLE
Failed Discord/etc thresholds not found, won't send notification + InfluxDB2\ApiException: [422] 

### ISSUE THREAD

**Issue by masterwishx** [alexjustesen/speedtest-tracker#1857]
using latest LSIO version in docker in Unraid

![image](https://github.com/user-attachments/assets/7c2c0e72-470a-4bc2-b63f-cc92ba83a3ad)

Also have : 

```
 production.INFO: InfluxDB2\ApiException: [422] Error connecting to the API (http://192.168.0.199:8086/api/v2/write?org=myORG&bucket=speedtest-tracker&precision=s)(failure writing points to database: partial write: field type conflict: input field "upload_jitter" on measurement "speedtest" is type integer, already exists as type float dropped=1) in /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php:164

Stack trace:
#0 /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php(221): InfluxDB2\DefaultApi->sendRequest()
#1 /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php(79): InfluxDB2\DefaultApi->request()
#2 /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/WriteApi.php(145): InfluxDB2\DefaultApi->post()
#3 [internal function]: InfluxDB2\WriteApi->InfluxDB2\{closure}()
#4 /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/WriteRetry.php(70): call_user_func()
#5 /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/WriteApi.php(144): InfluxDB2\WriteRetry->retry()
#6 /app/www/vendor/influxdata/influxdb-client-php/src/InfluxDB2/WriteApi.php(86): InfluxDB2\WriteApi->writeRaw()
#7 /app/www/app/Jobs/InfluxDBv2/WriteCompletedSpeedtest.php(62): InfluxDB2\WriteApi->write()
#8 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\InfluxDBv2\WriteCompletedSpeedtest->handle()
#9 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure()
#11 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#12 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\BoundMethod::call()
#13 /app/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(126): Illuminate\Container\Container->call()
#14 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#15 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /app/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(130): Illuminate\Pipeline\Pipeline->then()
#17 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#18 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#19 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Pipeline\Pipeline->then()
#21 /app/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#22 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\Queue\CallQueuedHandler->call()
#23 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(441): Illuminate\Queue\Jobs\Job->fire()
#24 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(391): Illuminate\Queue\Worker->process()
#25 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(178): Illuminate\Queue\Worker->runJob()
#26 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\Queue\Worker->daemon()
#27 /app/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\Queue\Console\WorkCommand->runWorker()
#28 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#29 /app/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#30 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure()
#31 /app/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#32 /app/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\Container\BoundMethod::call()
#33 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\Container\Container->call()
#34 /app/www/vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute()
#35 /app/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\Component\Console\Command\Command->run()
#36 /app/www/vendor/symfony/console/Application.php(1047): Illuminate\Console\Command->run()
#37 /app/www/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#38 /app/www/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#39 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\Component\Console\Application->run()
#40 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1205): Illuminate\Foundation\Console\Kernel->handle()
#41 /app/www/artisan(13): Illuminate\Foundation\Application->handleCommand()
#42 {main}  
```

**Comment by svenvg93** [comment]
For the influxdb error this is known in https://github.com/alexjustesen/speedtest-tracker/issues/1762, will be fix at some point. 

For the notifications; The only reason this error will show is when the thresholds are enabled but all set to 0. What you your threshold settings?

**Comment by masterwishx** [comment]
> For the influxdb error this is known in #1762, will be fix at some point.

Yes , also had issues in past and opened issues for it ....

> For the notifications; The only reason this error will show is when the thresholds are enabled but all set to 0. What you your threshold settings?

![image](https://github.com/user-attachments/assets/dc2437df-ec50-457b-8139-768030d52793)

**Comment by masterwishx** [comment]
> For the influxdb error this is known in #1762, will be fix at some point.

you are working for fix here #1802 ?

**Comment by svenvg93** [comment]
> > For the influxdb error this is known in #1762, will be fix at some point.
> 
> you are working for fix here #1802 ?

Yess we are working on refactoring the influx part 

@alexjustesen You got any idea why the threshold warnings are shown in the logs?

**Comment by alexjustesen** [comment]
If the write fails it's thrown into the logs here https://github.com/alexjustesen/speedtest-tracker/blob/main/app/Jobs/InfluxDBv2/WriteCompletedSpeedtest.php#L61-L67

**Comment by alexjustesen** [comment]
Closing as this was an Influxdb error not a Discord error.
