### ISSUE TITLE
Unable to boot with external postgres server

### ISSUE THREAD

**Issue by rameskum** [alexjustesen/speedtest-tracker#387]
**Describe the bug**
I was trying to configure an external Postgres database using docker-compose.yml
From the exception, it seems like the password is wrong, but I crossed checked quite a few times now, and it doesn't seems to be the case.

**To Reproduce**
Steps to reproduce the behaviour:
1. Using the below `dock-compose.yml` to deploy
```yaml
version: '3.6'

services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8766:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=pgsql
            - DB_HOST=${PG_HOST}
            - DB_PORT=${PG_PORT}
            - DB_DATABASE=${PG_DB}
            - DB_USERNAME=${PG_USER}
            - DB_PASSWORD=${PG_PASS}
        volumes:
            - '/docker/appdata/speedtest-tracker:/config'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
```

**Expected behaviour**
The container should start.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
-  Architecture: ams64
 - Browser: N/A
 - Version: Latest

**Screenshots**

**Logs**
```
[03-Feb-2023 22:43:20] NOTICE: systemd monitor interval set to 10000ms
🚛  Migrating the database...
[2023-02-03 22:43:21] production.ERROR: SQLSTATE[08006] [7] connection to server at "192.168.2.12", port 5432 failed: FATAL:  password authentication failed for user "speedtest"
connection to server at "192.168.2.12", port 5432 failed: FATAL:  password authentication failed for user "speedtest" (SQL: select * from information_schema.tables where table_catalog = speedtest_tracker and table_schema = public and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 7): SQLSTATE[08006] [7] connection to server at \"192.168.2.12\", port 5432 failed: FATAL:  password authentication failed for user \"speedtest\"
connection to server at \"192.168.2.12\", port 5432 failed: FATAL:  password authentication failed for user \"speedtest\" (SQL: select * from information_schema.tables where table_catalog = speedtest_tracker and table_schema = public and table_name = migrations and table_type = 'BASE TABLE') at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)

[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\\Database\\Connection->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(392): Illuminate\\Database\\Connection->select()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/PostgresBuilder.php(52): Illuminate\\Database\\Connection->selectFromWriteConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\PostgresBuilder->hasTable()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(682): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(138): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(247): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(157): retry()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(114): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(82): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(615): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(102): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call()
#19 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\\Component\\Console\\Command\\Command->run()
#21 /var/www/html/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#22 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#23 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#26 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}
[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"192.168.2.12\", port 5432 failed: FATAL:  password authentication failed for user \"speedtest\"
connection to server at \"192.168.2.12\", port 5432 failed: FATAL:  password authentication failed for user \"speedtest\" at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70)

[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(70): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/PostgresConnector.php(36): Illuminate\\Database\\Connectors\\Connector->createConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\PostgresConnector->connect()
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1181): call_user_func()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(486): Illuminate\\Database\\Connection->getPdo()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\\Database\\Connection->getPdoForSelect()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\\Database\\Connection->run()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(392): Illuminate\\Database\\Connection->select()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/PostgresBuilder.php(52): Illuminate\\Database\\Connection->selectFromWriteConnection()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\PostgresBuilder->hasTable()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(682): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(138): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(247): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(157): retry()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(114): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(82): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(615): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(102): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\\Container\\BoundMethod::call()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call()
#28 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\\Component\\Console\\Command\\Command->run()
#30 /var/www/html/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#31 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#32 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#35 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#36 {main}
"} 
In Connection.php line 760:
                                                                               
  SQLSTATE[08006] [7] connection to server at "192.168.2.12", port 5432 faile  
  d: FATAL:  password authentication failed for user "speedtest"               
  connection to server at "192.168.2.12", port 5432 failed: FATAL:  password   
  authentication failed for user "speedtest" (SQL: select * from information_  
  schema.tables where table_catalog = speedtest_tracker and table_schema = pu  
  blic and table_name = migrations and table_type = 'BASE TABLE')              
                                                                               
In Connector.php line 70:
                                                                               
  SQLSTATE[08006] [7] connection to server at "192.168.2.12", port 5432 faile  
  d: FATAL:  password authentication failed for user "speedtest"               
  connection to server at "192.168.2.12", port 5432 failed: FATAL:  password   
  authentication failed for user "speedtest"                                   
                                                                               
s6-rc: warning: unable to start service startup: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
[03-Feb-2023 22:43:21] NOTICE: Terminating ...
[03-Feb-2023 22:43:21] NOTICE: exiting, bye-bye!
```

**Comment by alexjustesen** [comment]
Can you double check your credentials using something like DBeaver?

**Comment by rameskum** [comment]
Yes, I verified more than twice.
I am attaching a short video for the same. I will change the password later.
[video](https://youtu.be/397bq4sdhUI)

**Comment by rameskum** [comment]
So I found the cause; the issue was in the password. I changed it not to include `#`, and it worked just fine.
