### ISSUE TITLE
The process has been signaled with signal "6".

### ISSUE THREAD

**Issue by axeloz** [alexjustesen/speedtest-tracker#508]
**Describe the bug**
Speedtest-cli not executed and tasks are sent to "failed_jobs" into the DB. 
The exception field contains: 
`Symfony\Component\Process\Exception\ProcessSignaledException: The process has been signaled with signal "6". in /www/speedtest-tracker/vendor/symfony/process/Process.php:436` 

**Expected behavior**
Tasks should be executed

**Environment (please complete the following information):**
 - OS: Ubuntu
-  Architecture: amd64
 - Browser: FF
 - Version latest

**Logs**
```
Symfony\Component\Process\Exception\ProcessSignaledException: The process has been signaled with signal "6". in /www/speedtest-tracker/vendor/symfony/process/Process.php:436
Stack trace:
#0 /www/speedtest-tracker/vendor/symfony/process/Process.php(249): Symfony\Component\Process\Process->wait()
#1 /www/speedtest-tracker/vendor/symfony/process/Process.php(266): Symfony\Component\Process\Process->run()
#2 /www/speedtest-tracker/app/Jobs/ExecSpeedtest.php(49): Symfony\Component\Process\Process->mustRun()
#3 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\ExecSpeedtest->handle()
#4 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#6 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#7 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call()
#8 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#9 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#10 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#12 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#13 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#14 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then()
#16 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#17 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#18 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\Queue\Jobs\Job->fire()
#19 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\Queue\Worker->process()
#20 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker->runJob()
#21 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(147): Illuminate\Queue\Worker->daemon()
#22 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(130): Illuminate\Queue\Console\WorkCommand->runWorker()
#23 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#24 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#26 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#27 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call()
#28 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call()
#29 /www/speedtest-tracker/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#30 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\Component\Console\Command\Command->run()
#31 /www/speedtest-tracker/vendor/symfony/console/Application.php(1022): Illuminate\Console\Command->run()
#32 /www/speedtest-tracker/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#33 /www/speedtest-tracker/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#34 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#35 /www/speedtest-tracker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run()
#36 /www/speedtest-tracker/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#37 {main}
```

**Additional context**
I tried to debug step-by-step. The `speedtest-cli` is installed and can be launched directly from the terminal including from the `www` user (`sudo -u www speedtest`). I also tried to create a `test.php` file with `<?php exec('speedtest')` and launch a `php ./test.php` and it works.
`speedtest-cli` was installed with `apt install`

If you have any idea. Thanks

**Comment by axeloz** [comment]
Well, I wanted to avoid using Docker so I installed it as a regular Laravel project but I failed. It works with Docker. 
Weird, it worked locally without Docker.

**Comment by alexjustesen** [comment]
TBH at this point "bare metal" installs aren't supported, Docker is preferred because I can hand off a complete environment I know the app works in, heck even my local dev env is containerized (Laravel Sail).

You _could_ following the regular Laravel install commands, but you'll also need... 
- cron to run the tasks
- supervisor to run the queue worker
- `speedtest-cli` installed and EULA accepted
- nginx or some other proxy to hit the php server

So it's just kind of way easier to use Docker.

**Comment by axeloz** [comment]
Thanks @alexjustesen, 
I tried on my local env first and I made it work while I couldn't on my prod env. Nevermind, I used Docker finally and it works, 

Thanks again
