### ISSUE TITLE
influxdb api + scheduler not working

### ISSUE THREAD

**Issue by batou069** [alexjustesen/speedtest-tracker#612]
**Describe the bug**
Scheduler not working
I setup scheduler for once per hour
setup influxdb (using free InfluxDB Cloud Serverless Version 2.0.0)
The API token I created for this in influx has ALL read/write permissions
In the logs I see an API error.
Not sure if additional configuration is needed inside of influxDB (like a telegraf) or i just need to open some ports in the docker-compose.yml file?

For now I only can do manual speed tests but no scheduler & no logging

**Expected behavior**
Pushing to influx db works, scheduler works

**Environment (please complete the following information):**
 - OS: 22.04 LTS (Jammy Jellyfish)
-  Architecture: x86_64
 - Version: latest
Linux docker 5.15.107-2-pve #1 SMP PVE 5.15.107-2 (2023-05-10T09:10Z) x86_64 x86_64 x86_64 GNU/Linux

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/98292364/57b466f9-74b3-4631-9ed2-0eb7bbe3c495)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/98292364/fa55a782-ac38-4c22-97fc-a632fd30c749)
![image](https://github.com/alexjustesen/speedtest-tracker/assets/98292364/4e85c451-99ad-42d1-a68a-13f50644793c)

**Logs**
```
[2023-05-22 12:27:18] production.ERROR: GuzzleHttp\Exception\ClientException: Client error: `POST https://us-east-1-1.aws.cloud2.influxdata.com/api/v2/write?org=homelab&bucket=speedtest&precision=s` resulted in a `400 Bad Request` response:
{"code":"invalid","message":"failed to parse line protocol: error writing line 1: Unable to insert iox::column_type::fie (truncated...)

 in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
#1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(159): GuzzleHttp\Promise\TaskQueue->run()
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(184): GuzzleHttp\Handler\CurlMultiHandler->tick()
#6 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute()
#7 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php(107): GuzzleHttp\Promise\Promise->wait()
#12 /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/DefaultApi.php(83): InfluxDB2\DefaultApi->request()
#13 /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/WriteApi.php(145): InfluxDB2\DefaultApi->post()
#14 [internal function]: InfluxDB2\WriteApi->InfluxDB2\{closure}()
#15 /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/WriteRetry.php(70): call_user_func()
#16 /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/WriteApi.php(146): InfluxDB2\WriteRetry->retry()
#17 /var/www/html/vendor/influxdata/influxdb-client-php/src/InfluxDB2/WriteApi.php(86): InfluxDB2\WriteApi->writeRaw()
#18 /var/www/html/app/Jobs/SendDataToInfluxDbV2.php(68): InfluxDB2\WriteApi->write()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\SendDataToInfluxDbV2->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(434): Illuminate\Queue\Jobs\Job->fire()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(384): Illuminate\Queue\Worker->process()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(175): Illuminate\Queue\Worker->runJob()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\Queue\Worker->daemon()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\Queue\Console\WorkCommand->runWorker()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\Container\Container->call()
#45 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(164): Symfony\Component\Console\Command\Command->run()
#47 /var/www/html/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#48 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#49 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\Component\Console\Application->run()
#51 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#52 {main}
```

**Comment by alexjustesen** [comment]
Going to track this in #621
