### ISSUE TITLE
shell_exec(): Unable to execute 'stty 2> /dev/null'

### ISSUE THREAD

**Issue by ChanceM** [alexjustesen/speedtest-tracker#681]
**Describe the bug**
Failure when generating app key

**To Reproduce**
1. Run Docker Compose Install
2. Review Docker Logs 
3. See error

**Expected behavior**
Expected the app to start successfully.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
-  Architecture: amd64
 - Browser chrome
 - Version latest

**Logs**
```
s6-rc-compile: tracing: from s6-rc-compile internals: adding identifier s6rc-oneshot-runner of type longrun
s6-rc-compile: tracing: from s6-rc-compile internals: adding identifier s6rc-fdholder of type longrun
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/configure-ssl
s6-rc-compile: info: configure-ssl has type oneshot
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier configure-ssl of type oneshot
s6-rc-compile: tracing: from configure-ssl: adding identifier runas-user of type unknown
s6-rc-compile: tracing: dependency from configure-ssl to runas-user (48)
s6-rc-compile: tracing: dependency from configure-ssl to s6rc-oneshot-runner (0)
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/cron
s6-rc-compile: info: cron has type longrun
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier cron of type longrun
s6-rc-compile: tracing: from cron: adding identifier laravel-automations of type unknown
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/debug-nginx
s6-rc-compile: info: debug-nginx has type oneshot
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier debug-nginx of type oneshot
s6-rc-compile: tracing: from debug-nginx: adding identifier runas-user of type unknown
s6-rc-compile: tracing: identifier runas-user was already declared with type unknown
s6-rc-compile: tracing: dependency from debug-nginx to runas-user (48)
s6-rc-compile: tracing: dependency from debug-nginx to s6rc-oneshot-runner (0)
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/laravel-automations
s6-rc-compile: info: laravel-automations has type oneshot
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier laravel-automations of type oneshot
s6-rc-compile: tracing: previously encountered identifier laravel-automations now has type oneshot
s6-rc-compile: tracing: from laravel-automations: adding identifier runas-user of type unknown
s6-rc-compile: tracing: identifier runas-user was already declared with type unknown
s6-rc-compile: tracing: from laravel-automations: adding identifier configure-ssl of type unknown
s6-rc-compile: tracing: identifier configure-ssl was already declared with type oneshot
s6-rc-compile: tracing: dependency from laravel-automations to runas-user (48)
s6-rc-compile: tracing: dependency from laravel-automations to configure-ssl (34)
s6-rc-compile: tracing: dependency from laravel-automations to s6rc-oneshot-runner (0)
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/msmtp
s6-rc-compile: info: msmtp has type oneshot
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier msmtp of type oneshot
s6-rc-compile: tracing: dependency from msmtp to s6rc-oneshot-runner (0)
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/nginx
s6-rc-compile: info: nginx has type longrun
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier nginx of type longrun
s6-rc-compile: tracing: from nginx: adding identifier php-fpm of type unknown
s6-rc-compile: tracing: from nginx: adding identifier configure-ssl of type unknown
s6-rc-compile: tracing: identifier configure-ssl was already declared with type oneshot
s6-rc-compile: tracing: from nginx: adding identifier debug-nginx of type unknown
s6-rc-compile: tracing: identifier debug-nginx was already declared with type oneshot
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/php-fpm
s6-rc-compile: info: php-fpm has type longrun
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier php-fpm of type longrun
s6-rc-compile: tracing: previously encountered identifier php-fpm now has type longrun
s6-rc-compile: tracing: from php-fpm: adding identifier runas-user of type unknown
s6-rc-compile: tracing: identifier runas-user was already declared with type unknown
s6-rc-compile: tracing: from php-fpm: adding identifier laravel-automations of type unknown
s6-rc-compile: tracing: identifier laravel-automations was already declared with type oneshot
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/queue-worker
s6-rc-compile: info: queue-worker has type longrun
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier queue-worker of type longrun
s6-rc-compile: tracing: from queue-worker: adding identifier laravel-automations of type unknown
s6-rc-compile: tracing: identifier laravel-automations was already declared with type oneshot
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/runas-user
s6-rc-compile: info: runas-user has type oneshot
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier runas-user of type oneshot
s6-rc-compile: tracing: previously encountered identifier runas-user now has type oneshot
s6-rc-compile: tracing: dependency from runas-user to s6rc-oneshot-runner (0)
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/user
s6-rc-compile: info: user has type bundle
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier user of type bundle
s6-rc-compile: tracing: from user: adding identifier cron of type unknown
s6-rc-compile: tracing: identifier cron was already declared with type longrun
s6-rc-compile: tracing: from user: adding identifier queue-worker of type unknown
s6-rc-compile: tracing: identifier queue-worker was already declared with type longrun
s6-rc-compile: tracing: from user: adding identifier debug-nginx of type unknown
s6-rc-compile: tracing: identifier debug-nginx was already declared with type oneshot
s6-rc-compile: tracing: from user: adding identifier msmtp of type unknown
s6-rc-compile: tracing: identifier msmtp was already declared with type oneshot
s6-rc-compile: tracing: from user: adding identifier nginx of type unknown
s6-rc-compile: tracing: identifier nginx was already declared with type longrun
s6-rc-compile: tracing: from user: adding identifier configure-ssl of type unknown
s6-rc-compile: tracing: identifier configure-ssl was already declared with type oneshot
s6-rc-compile: tracing: from user: adding identifier laravel-automations of type unknown
s6-rc-compile: tracing: identifier laravel-automations was already declared with type oneshot
s6-rc-compile: tracing: from user: adding identifier php-fpm of type unknown
s6-rc-compile: tracing: identifier php-fpm was already declared with type longrun
s6-rc-compile: tracing: from user: adding identifier runas-user of type unknown
s6-rc-compile: tracing: identifier runas-user was already declared with type oneshot
s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/user2
s6-rc-compile: info: user2 has type bundle
s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier user2 of type bundle
s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources/base
s6-rc-compile: info: base has type bundle
s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources: adding identifier base of type bundle
s6-rc-compile: tracing: from base: adding identifier legacy-cont-init of type unknown
s6-rc-compile: tracing: from base: adding identifier fix-attrs of type unknown
s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources/fix-attrs
s6-rc-compile: info: fix-attrs has type oneshot
s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources: adding identifier fix-attrs of type oneshot
s6-rc-compile: tracing: previously encountered identifier fix-attrs now has type oneshot
s6-rc-compile: tracing: dependency from fix-attrs to s6rc-oneshot-runner (0)
s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources/legacy-cont-init
s6-rc-compile: info: legacy-cont-init has type oneshot
s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources: adding identifier legacy-cont-init of type oneshot
s6-rc-compile: tracing: previously encountered identifier legacy-cont-init now has type oneshot
s6-rc-compile: tracing: from legacy-cont-init: adding identifier fix-attrs of type unknown
s6-rc-compile: tracing: identifier fix-attrs was already declared with type oneshot
s6-rc-compile: tracing: dependency from legacy-cont-init to fix-attrs (162)
s6-rc-compile: tracing: dependency from legacy-cont-init to s6rc-oneshot-runner (0)
s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources/legacy-services
s6-rc-compile: info: legacy-services has type oneshot
s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources: adding identifier legacy-services of type oneshot
s6-rc-compile: tracing: from legacy-services: adding identifier user of type unknown
s6-rc-compile: tracing: identifier user was already declared with type bundle
s6-rc-compile: tracing: from legacy-services: adding identifier base of type unknown
s6-rc-compile: tracing: identifier base was already declared with type bundle
s6-rc-compile: tracing: dependency from legacy-services to user (129)
s6-rc-compile: tracing: dependency from legacy-services to base (140)
s6-rc-compile: tracing: dependency from legacy-services to s6rc-oneshot-runner (0)
s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources/top
s6-rc-compile: info: top has type bundle
s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.2.1/etc/s6-rc/sources: adding identifier top of type bundle
s6-rc-compile: tracing: from top: adding identifier user of type unknown
s6-rc-compile: tracing: identifier user was already declared with type bundle
s6-rc-compile: tracing: from top: adding identifier base of type unknown
s6-rc-compile: tracing: identifier base was already declared with type bundle
s6-rc-compile: tracing: from top: adding identifier legacy-services of type unknown
s6-rc-compile: tracing: identifier legacy-services was already declared with type oneshot
s6-rc-compile: tracing: from top: adding identifier user2 of type unknown
s6-rc-compile: tracing: identifier user2 was already declared with type bundle
s6-rc-compile: info: making bundles for pipelines
s6-rc-compile: info: resolving bundle names
s6-rc-compile: info: converting bundle array
s6-rc-compile: info: resolving service names
s6-rc-compile: tracing: cron depends on oneshot laravel-automations (8)
s6-rc-compile: tracing: nginx depends on longrun php-fpm (4)
s6-rc-compile: tracing: nginx depends on oneshot configure-ssl (6)
s6-rc-compile: tracing: nginx depends on oneshot debug-nginx (7)
s6-rc-compile: tracing: php-fpm depends on oneshot runas-user (10)
s6-rc-compile: tracing: php-fpm depends on oneshot laravel-automations (8)
s6-rc-compile: tracing: queue-worker depends on oneshot laravel-automations (8)
s6-rc-compile: tracing: configure-ssl depends on oneshot runas-user (10)
s6-rc-compile: tracing: configure-ssl depends on longrun s6rc-oneshot-runner (0)
s6-rc-compile: tracing: debug-nginx depends on oneshot runas-user (10)
s6-rc-compile: tracing: debug-nginx depends on longrun s6rc-oneshot-runner (0)
s6-rc-compile: tracing: laravel-automations depends on oneshot runas-user (10)
s6-rc-compile: tracing: laravel-automations depends on oneshot configure-ssl (6)
s6-rc-compile: tracing: laravel-automations depends on longrun s6rc-oneshot-runner (0)
s6-rc-compile: tracing: msmtp depends on longrun s6rc-oneshot-runner (0)
s6-rc-compile: tracing: runas-user depends on longrun s6rc-oneshot-runner (0)
s6-rc-compile: tracing: fix-attrs depends on longrun s6rc-oneshot-runner (0)
s6-rc-compile: tracing: legacy-cont-init depends on oneshot fix-attrs (11)
s6-rc-compile: tracing: legacy-cont-init depends on longrun s6rc-oneshot-runner (0)
s6-rc-compile: tracing: legacy-services depends on bundle user
s6-rc-compile: tracing: legacy-services depends on bundle base
s6-rc-compile: tracing: legacy-services depends on longrun s6rc-oneshot-runner (0)
s6-rc-compile: info: converting service dependency array
s6-rc-compile: info: checking database correctness
s6-rc-compile: info: writing compiled information to /run/s6/db
s6-rc-compile: info: writing /run/s6/db/n
s6-rc-compile: info: writing /run/s6/db/resolve.cdb
s6-rc-compile: info: writing /run/s6/db/db
s6-rc-compile: info: writing /run/s6/db/servicedirs
s6-rc: info: bringing selected services up
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service runas-user: starting
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-rc: info: service msmtp: starting
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-rc: info: service msmtp successfully started
s6-rc: info: service legacy-cont-init successfully started
usermod: no changes

--------------------------------------------------------------------

_______                       __ __                __
|     __|.-----.-----.-----.--|  |  |_.-----.-----.|  |_
|__     ||  _  |  -__|  -__|  _  |   _|  -__|__ --||   _|
|_______||   __|_____|_____|_____|____|_____|_____||____|
|__|
_______                   __
|_     _|.----.---.-.----.|  |--.-----.----.
|   |  |   _|  _  |  __||    <|  -__|   _|
|___|  |__| |___._|____||__|__|_____|__|


--------------------------------------------------------------------

To support Speedtest Tracker visit:
https://github.com/alexjustesen/speedtest-tracker
-------------------------------------
GID/UID
-------------------------------------

User uid:    5001
User gid:    5001
-------------------------------------

s6-rc: info: service runas-user successfully started
s6-rc: info: service debug-nginx: starting
s6-rc: info: service configure-ssl: starting
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
s6-rc: info: service configure-ssl successfully started
s6-rc: info: service laravel-automations: starting
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
🔥 NGINX and PHP-FPM are in DEBUG MODE 🔥s6-rc: info: service debug-nginx successfully started

🐇  Configuring Speedtest Tracker...

🔒  Fixing app path file permissions...
✅  Permissions fixed.

✅  Database already exists.

🔗  Creating database symlink...
✅  Database symlink created.

✅  Environment file exists.

🔗  Creating symlinks for config and log files...
✅  Symlinks created.

⏳  Generating app key...
[2023-08-15 05:01:42] production.ERROR: shell_exec(): Unable to execute 'stty 2> /dev/null' {"exception":"[object] (ErrorException(code: 0): shell_exec(): Unable to execute 'stty 2> /dev/null' at /var/www/html/vendor/symfony/console/Terminal.php:131)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/symfony/console/Terminal.php(131): shell_exec()
#3 /var/www/html/vendor/symfony/console/Application.php(1009): Symfony\\Component\\Console\\Terminal::hasSttyAvailable()
#4 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#5 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
#7 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"}

In Terminal.php line 131:

shell_exec(): Unable to execute 'stty 2> /dev/null'


s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: bringing selected services down
s6-rc: info: service legacy-services: already down
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service msmtp: stopping
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-rc: info: service queue-worker: already down
s6-rc: info: service nginx: already down
s6-rc: info: service debug-nginx: stopping
s6-rc: info: service php-fpm: already down
s6-rc: info: service cron: already down
s6-rc: info: service laravel-automations: already down
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-rc: info: service configure-ssl: stopping
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-rc: info: service debug-nginx successfully stopped
s6-rc: info: service msmtp successfully stopped
s6-rc: info: service configure-ssl successfully stopped
s6-rc: info: service runas-user: stopping
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-rc: info: service runas-user successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by alexjustesen** [comment]
Closing as this should be fixed when that PR is merged, if it needs to be re-opened just tag me.

**Comment by alexjustesen** [comment]
@ChanceM can you share a copy of your `docker-compose.yml` file?

**Comment by alexjustesen** [comment]
Using `sqlite` as the DB you'll also want to pass `/config/database.sql` as the value for `DB_HOST=`.

**Comment by ChanceM** [comment]
That worked, then when accessing Setting>General I get a 500. So I decided to switch to Postgres since that seems like the supported route, but I still get a 500 when going to Setting>General. Let me know if you want me to open a separate issue.

**Comment by ChanceM** [comment]
DB Logs:
```
2023-09-05 21:03:08.929 UTC [1] LOG:  starting PostgreSQL 15.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-09-05 21:03:08.929 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-09-05 21:03:08.929 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-09-05 21:03:08.935 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-09-05 21:03:08.944 UTC [16] LOG:  database system was shut down at 2023-09-05 21:03:08 UTC
2023-09-05 21:03:08.950 UTC [1] LOG:  database system is ready to accept connections
2023-09-05 21:03:24.753 UTC [20] ERROR:  relation "settings" does not exist at character 31
2023-09-05 21:03:24.753 UTC [20] STATEMENT:  select "name", "payload" from "settings" where "group" = $1
2023-09-05 21:03:25.005 UTC [21] ERROR:  relation "settings" does not exist at character 31
2023-09-05 21:03:25.005 UTC [21] STATEMENT:  select "name", "payload" from "settings" where "group" = $1
2023-09-05 21:03:25.253 UTC [22] ERROR:  relation "settings" does not exist at character 31
2023-09-05 21:03:25.253 UTC [22] STATEMENT:  select "name", "payload" from "settings" where "group" = $1
2023-09-05 21:03:25.341 UTC [23] ERROR:  relation "settings" does not exist at character 31
2023-09-05 21:03:25.341 UTC [23] STATEMENT:  select "name", "payload" from "settings" where "group" = $1
2023-09-05 21:03:25.372 UTC [24] ERROR:  relation "settings" does not exist at character 31
2023-09-05 21:03:25.372 UTC [24] STATEMENT:  select "name", "payload" from "settings" where "group" = $1
2023-09-05 21:03:25.576 UTC [25] ERROR:  relation "settings" does not exist at character 31
2023-09-05 21:03:25.576 UTC [25] STATEMENT:  select "name", "payload" from "settings" where "group" = $1
```

**Comment by alexjustesen** [comment]
> That worked, then when accessing Setting>General I get a 500. So I decided to switch to Postgres since that seems like the supported route, but I still get a 500 when going to Setting>General. Let me know if you want me to open a separate issue.

It's like that a setting got missed or got corrupt for some reason. If you don't mind nuking your data from the cli you can run `php artisan app:install --force` or wait for a future release (soon(ish)) I can create a `app:reset-settings` command to fix that issue. 

By the database issue it looks like Postgresql might not like something in the query builder when it comes to reading from the settings page.

**Comment by ChanceM** [comment]
I tired wiping the DB and the app and re-running. Same effect, this error (below) is streaming about every second still.

Also tried: `docker exec speedtest-tracker php artisan app:install --force`
```
Starting to install the application...

⏳ Optimizing the cache...
✅ Optimized cache

⏳ Migrating the database...
✅ Database migrated

🚀 Finished installing the application!
```

Logs from speedtest-tracker:
```
In Terminal.php line 131:
                                                       
  shell_exec(): Unable to execute 'stty 2> /dev/null'  
                                                       

[2023-09-06 03:49:45] production.ERROR: shell_exec(): Unable to execute 'stty 2> /dev/null' {"exception":"[object] (ErrorException(code: 0): shell_exec(): Unable to execute 'stty 2> /dev/null' at /var/www/html/vendor/symfony/console/Terminal.php:131)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/symfony/console/Terminal.php(131): shell_exec()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(114): Symfony\\Component\\Console\\Terminal::hasSttyAvailable()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#10 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#12 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#13 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#14 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#16 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#17 {main}
"} 
```
New Docker File
```
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8085:80/tcp
      - 8448:443/tcp
    environment:
      - PUID=5001
      - PGID=5001
      - TZ=America/Los_Angeles
        #- DB_CONNECTION=sqlite
        #- DB_HOST=/config/database.sqlite
        #- DEBUG_OUTPUT=true
        #- S6_VERBOSITY=5
      - DB_CONNECTION=pgsql
      - DB_HOST=sp-db
      - DB_PORT=5432
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=speedy
      - DB_PASSWORD=AwsomePasswordHere
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/speedtest/config:/config
      - /docker/speedtest/web:/etc/ssl/web
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    restart: unless-stopped
    depends_on:
      - sp-db
  sp-db:
    image: docker.io/postgres:15-alpine
    user: 5001:5001
    container_name: sp-db
    restart: always
    environment:
      - POSTGRES_DB=speedtest_tracker
      - POSTGRES_USER=speedy
      - POSTGRES_PASSWORD=AwsomePasswordHere
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/docker_data/sp-postgresql/db:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
```

**Comment by ChanceM** [comment]
Per the discussion here: https://github.com/alexjustesen/speedtest-tracker/discussions/541 I updated my docker version. Everything is working now. Sorry for the headache, but your next round is on me.
