### ISSUE TITLE
Lost old SQLite Data With 0.11.19

### ISSUE THREAD

**Issue by corasaniti** [alexjustesen/speedtest-tracker#702]
**Describe the bug**
Update to version 0.11.19 

**To Reproduce**
Run with this docker run
docker run -d --name speedtest-alexjustesen \
    -p 8890:443 \
    -p 8443:443 \
    -e PUID=1000 \
    -e PGID=1000 \
    -e TELEGRAM_BOT_TOKEN=xxxxxxx-xxxxxx-xxxxx-xxxx\
    -v ${PWD}/config:/config \
    --restart unless-stopped \
    ghcr.io/alexjustesen/speedtest-tracker:latest

**Expected behavior**
Keep previous SQLite data

**Log**
This is part of logerror
```
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(951): Illuminate\\Database\\Connection->runQueryCallback()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(931): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(758): Illuminate\\Database\\Connection->handleQueryException()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(424): Illuminate\\Database\\Connection->run()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(394): Illuminate\\Database\\Connection->select()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(44): Illuminate\\Database\\Connection->selectFromWriteConnection()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(159): retry()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(104): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#31 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#33 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#34 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#35 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#37 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#38 {main}
"} 
In Connection.php line 801:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select *  
   from information_schema.tables where table_schema = speedtest_tracker and   
  table_name = migrations and table_type = 'BASE TABLE')                       
                                                                               
In Connector.php line 65:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
usermod: no changes
```

**Environment (please complete the following information):**
 - OS:Debian bullsseye
-  Architecture:amd64
 - Browser chrome, opera
 - Version v.0.11.19

**Comment by spupuz** [comment]
Since last upgrade I can't login, don't see errors using Sql too

**Comment by Thunder7ga** [comment]
Getting this one too....

**Comment by alexjustesen** [comment]
Same as #701, https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.20 rolling out to fix this
