### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused 

### ISSUE THREAD

**Issue by 1alessandro1** [alexjustesen/speedtest-tracker#784]
**Describe the bug**
I was setting up the docker container with docker compose, as explained in the docs. 

**Expected behavior**
No errors upon starting

**Environment (please complete the following information):**
 - OS: Armbian
-  Architecture: aarch64
 - Browser: Firefox

**Screenshots**

![image](https://github.com/alexjustesen/speedtest-tracker/assets/46293832/583b5cc9-21b1-4db2-9186-28e7060ac6c7)

**Logs**

<details>
  <summary>Check the spoiler</summary>

  ```
2023-09-19T00:03:21.558831844Z #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1292): call_user_func()
2023-09-19T00:03:21.558851385Z #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\\Database\\Connection->getPdo()
2023-09-19T00:03:21.558880510Z #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\\Database\\Connection->getPdoForSelect()
2023-09-19T00:03:21.558902843Z #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(788): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
2023-09-19T00:03:21.558930884Z #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(951): Illuminate\\Database\\Connection->runQueryCallback()
2023-09-19T00:03:21.558953217Z #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(930): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection()
2023-09-19T00:03:21.559053383Z #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(757): Illuminate\\Database\\Connection->handleQueryException()
2023-09-19T00:03:21.559091466Z #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\\Database\\Connection->run()
2023-09-19T00:03:21.559111382Z #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(394): Illuminate\\Database\\Connection->select()
2023-09-19T00:03:21.559130466Z #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(43): Illuminate\\Database\\Connection->selectFromWriteConnection()
2023-09-19T00:03:21.559153549Z #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
2023-09-19T00:03:21.559173965Z #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
2023-09-19T00:03:21.559194632Z #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
2023-09-19T00:03:21.559214381Z #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
2023-09-19T00:03:21.559235256Z #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): retry()
2023-09-19T00:03:21.559269797Z #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
2023-09-19T00:03:21.559303880Z #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
2023-09-19T00:03:21.559324047Z #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
2023-09-19T00:03:21.559345672Z #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
2023-09-19T00:03:21.559374713Z #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
2023-09-19T00:03:21.559397213Z #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
2023-09-19T00:03:21.559417254Z #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
2023-09-19T00:03:21.559442504Z #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
2023-09-19T00:03:21.559581461Z #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
2023-09-19T00:03:21.559624335Z #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
2023-09-19T00:03:21.559644335Z #31 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
2023-09-19T00:03:21.559663418Z #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
2023-09-19T00:03:21.559689543Z #33 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
2023-09-19T00:03:21.559709334Z #34 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
2023-09-19T00:03:21.559736959Z #35 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
2023-09-19T00:03:21.559758542Z #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
2023-09-19T00:03:21.559777875Z #37 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
2023-09-19T00:03:21.559796167Z #38 {main}
2023-09-19T00:03:21.559812583Z "} 
2023-09-19T00:03:21.558906468Z 
2023-09-19T00:03:21.580934150Z In Connection.php line 801:
2023-09-19T00:03:21.581070356Z                                                                                
2023-09-19T00:03:21.581124772Z   SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select *  
2023-09-19T00:03:21.581148772Z    from information_schema.tables where table_schema = speedtest_tracker and   
2023-09-19T00:03:21.581180689Z   table_name = migrations and table_type = 'BASE TABLE')                       
2023-09-19T00:03:21.581201147Z                                                                                
2023-09-19T00:03:21.581219646Z 
2023-09-19T00:03:21.581950930Z In Connector.php line 65:
2023-09-19T00:03:21.582075679Z                                              
2023-09-19T00:03:21.582124137Z   SQLSTATE[HY000] [2002] Connection refused  
2023-09-19T00:03:21.582155345Z                                              
2023-09-19T00:03:21.582176178Z 
2023-09-19T00:03:21.648159724Z s6-rc: warning: unable to start service laravel-automations: command exited 1
2023-09-19T00:03:24.102552446Z /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
2023-09-19T00:03:26.452226327Z prog: fatal: stopping the container.
2023-09-19T00:05:14.438047810Z usermod: no changes
2023-09-19T00:05:14.446948382Z 
2023-09-19T00:05:14.447120838Z --------------------------------------------------------------------
2023-09-19T00:05:14.447172254Z 
2023-09-19T00:05:14.447199129Z  _______                       __ __                __
2023-09-19T00:05:14.447224379Z |     __|.-----.-----.-----.--|  |  |_.-----.-----.|  |_
2023-09-19T00:05:14.447246837Z |__     ||  _  |  -__|  -__|  _  |   _|  -__|__ --||   _|
2023-09-19T00:05:14.447269878Z |_______||   __|_____|_____|_____|____|_____|_____||____|
2023-09-19T00:05:14.447292920Z          |__|
2023-09-19T00:05:14.447314045Z  _______                   __
2023-09-19T00:05:14.447335003Z |_     _|.----.---.-.----.|  |--.-----.----.
2023-09-19T00:05:14.447357961Z   |   |  |   _|  _  |  __||    <|  -__|   _|
2023-09-19T00:05:14.447380335Z   |___|  |__| |___._|____||__|__|_____|__|
2023-09-19T00:05:14.447402252Z 
2023-09-19T00:05:14.447422460Z 
2023-09-19T00:05:14.447443085Z --------------------------------------------------------------------
2023-09-19T00:05:14.447464751Z 
2023-09-19T00:05:14.447484959Z To support Speedtest Tracker visit:
2023-09-19T00:05:14.447582000Z https://github.com/alexjustesen/speedtest-tracker
2023-09-19T00:05:14.447637124Z -------------------------------------
2023-09-19T00:05:14.447664957Z GID/UID
2023-09-19T00:05:14.447686166Z -------------------------------------
2023-09-19T00:05:14.463302749Z 
2023-09-19T00:05:14.463478122Z User uid:    1000
2023-09-19T00:05:14.463637037Z User gid:    1000
2023-09-19T00:05:14.463686495Z -------------------------------------
2023-09-19T00:05:14.463712203Z 
2023-09-19T00:05:14.483932112Z 🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
2023-09-19T00:05:15.735959625Z 
2023-09-19T00:05:15.736103457Z 🐇  Configuring Speedtest Tracker...
2023-09-19T00:05:15.736149331Z 
2023-09-19T00:05:15.736169456Z 🔒  Fixing app path file permissions...
2023-09-19T00:05:15.765810806Z ✅  Permissions fixed.
2023-09-19T00:05:15.765981888Z 
2023-09-19T00:05:15.766620423Z ✅  Environment file exists.
2023-09-19T00:05:15.766856295Z 
2023-09-19T00:05:15.766912336Z 🔗  Creating symlinks for config and log files...
2023-09-19T00:05:15.769139937Z ✅  Symlinks created.
2023-09-19T00:05:15.769274728Z 
2023-09-19T00:05:15.775467745Z ✅  App key exists
2023-09-19T00:05:15.775671951Z 
2023-09-19T00:05:15.775731784Z 💰  Building the cache...
2023-09-19T00:05:20.031938151Z ✅  Cache set.
2023-09-19T00:05:20.032201982Z 
2023-09-19T00:05:20.032264231Z 🚛  Migrating the database...
2023-09-19T00:05:47.822651889Z ✅  Database migrated.
2023-09-19T00:05:47.822846262Z 
2023-09-19T00:05:47.822886678Z ✅  All set, Speedtest Tracker started.
2023-09-19T00:05:47.822912386Z 
2023-09-19T00:05:48.278530357Z [18-Sep-2023 19:05:48] NOTICE: fpm is running, pid 112
2023-09-19T00:05:48.278705730Z [18-Sep-2023 19:05:48] NOTICE: ready to handle connections
2023-09-19T00:05:48.294084482Z [18-Sep-2023 19:05:48] NOTICE: systemd monitor interval set to 10000ms
2023-09-19T00:05:49.089432994Z ❌ There seems to be a failure in checking the web server + PHP-FPM. Here's the response:
2023-09-19T00:05:49.090418484Z 
  ```

Docker containers: 

```
CONTAINER ID   IMAGE                                           COMMAND                  CREATED          STATUS          PORTS                                                                                      NAMES
895e9bd3aadb   ghcr.io/alexjustesen/speedtest-tracker:latest   "/init"                  16 minutes ago   Up 8 minutes    9000/tcp, 0.0.0.0:8080->80/tcp, :::8080->80/tcp, 0.0.0.0:8443->443/tcp, :::8443->443/tcp   speedtest-tracker
2f9eac67aa53   mariadb:10                                      "docker-entrypoint.s…"   18 minutes ago   Up 16 minutes   3306/tcp                                                                                   speedtest-tracker_db_1

```

Docker logs (mariadb):

```
2023-09-19T00:01:56.824648542Z 2023-09-19  0:01:56 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2023-09-19T00:01:56.829023995Z 2023-09-19  0:01:56 0 [Note] InnoDB: log sequence number 46878; transaction id 14
2023-09-19T00:01:56.829404616Z 2023-09-19  0:01:56 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-09-19T00:01:56.842446768Z 2023-09-19  0:01:56 0 [Warning] 'user' entry 'root@2f9eac67aa53' ignored in --skip-name-resolve mode.
2023-09-19T00:01:56.842756140Z 2023-09-19  0:01:56 0 [Warning] 'proxies_priv' entry '@% root@2f9eac67aa53' ignored in --skip-name-resolve mode.
2023-09-19T00:01:56.878582924Z 2023-09-19  0:01:56 0 [Note] mariadbd: ready for connections.
2023-09-19T00:01:56.878710006Z Version: '10.11.5-MariaDB-1:10.11.5+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
2023-09-19T00:01:57.460512422Z 2023-09-19 00:01:57+00:00 [Note] [Entrypoint]: Temporary server started.
2023-09-19T00:05:02.015724054Z 2023-09-19 00:05:02+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: =N^p+VPV.8sFC:RdKE!E%PgNxh"O*RZd
2023-09-19T00:05:02.044281874Z 2023-09-19 00:05:02+00:00 [Note] [Entrypoint]: Creating database speedtest_tracker
2023-09-19T00:05:02.052581327Z 2023-09-19 00:05:02+00:00 [Note] [Entrypoint]: Creating user speedy
2023-09-19T00:05:02.063495294Z 2023-09-19 00:05:02+00:00 [Note] [Entrypoint]: Giving user speedy access to schema speedtest_tracker
2023-09-19T00:05:02.072188076Z 2023-09-19 00:05:02+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
2023-09-19T00:05:09.397882018Z 
2023-09-19T00:05:09.406237595Z 2023-09-19 00:05:09+00:00 [Note] [Entrypoint]: Stopping temporary server
2023-09-19T00:05:09.407396000Z 2023-09-19  0:05:09 0 [Note] mariadbd (initiated by: unknown): Normal shutdown
2023-09-19T00:05:09.428375067Z 2023-09-19  0:05:09 0 [Note] InnoDB: FTS optimize thread exiting.
2023-09-19T00:05:11.822492850Z 2023-09-19  0:05:11 0 [Note] InnoDB: Starting shutdown...
2023-09-19T00:05:11.822871929Z 2023-09-19  0:05:11 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2023-09-19T00:05:11.823998667Z 2023-09-19  0:05:11 0 [Note] InnoDB: Buffer pool(s) dump completed at 230919  0:05:11
2023-09-19T00:05:12.073231673Z 2023-09-19  0:05:12 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2023-09-19T00:05:12.073521754Z 2023-09-19  0:05:12 0 [Note] InnoDB: Shutdown completed; log sequence number 46878; transaction id 15
2023-09-19T00:05:14.444815655Z 2023-09-19  0:05:14 0 [Note] mariadbd: Shutdown complete
2023-09-19T00:05:14.445290358Z 
2023-09-19T00:05:14.476427275Z 2023-09-19 00:05:14+00:00 [Note] [Entrypoint]: Temporary server stopped
2023-09-19T00:05:14.476588607Z 
2023-09-19T00:05:14.485874675Z 2023-09-19 00:05:14+00:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.
2023-09-19T00:05:14.486572501Z 
2023-09-19T00:05:15.802516206Z 2023-09-19  0:05:15 0 [Note] Starting MariaDB 10.11.5-MariaDB-1:10.11.5+maria~ubu2204 source revision 7875294b6b74b53dd3aaa723e6cc103d2bb47b2c as process 1
2023-09-19T00:05:16.189916197Z 2023-09-19  0:05:16 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2023-09-19T00:05:16.195067933Z 2023-09-19  0:05:16 0 [Note] InnoDB: Number of transaction pools: 1
2023-09-19T00:05:16.195195807Z 2023-09-19  0:05:16 0 [Note] InnoDB: Using ARMv8 crc32 + pmull instructions
2023-09-19T00:05:16.195322222Z 2023-09-19  0:05:16 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2023-09-19T00:05:16.197592865Z 2023-09-19  0:05:16 0 [Note] InnoDB: Using liburing
2023-09-19T00:05:16.198979058Z 2023-09-19  0:05:16 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2023-09-19T00:05:16.203853131Z 2023-09-19  0:05:16 0 [Note] InnoDB: Completed initialization of buffer pool
2023-09-19T00:05:16.336622256Z 2023-09-19  0:05:16 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2023-09-19T00:05:16.360415294Z 2023-09-19  0:05:16 0 [Note] InnoDB: End of log at LSN=46878
2023-09-19T00:05:16.560415993Z 2023-09-19  0:05:16 0 [Note] InnoDB: 128 rollback segments are active.
2023-09-19T00:05:16.567808289Z 2023-09-19  0:05:16 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2023-09-19T00:05:16.567943454Z 2023-09-19  0:05:16 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2023-09-19T00:05:16.567981328Z 2023-09-19  0:05:16 0 [Note] InnoDB: log sequence number 46878; transaction id 14
2023-09-19T00:05:16.568931443Z 2023-09-19  0:05:16 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2023-09-19T00:05:16.569068275Z 2023-09-19  0:05:16 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-09-19T00:05:16.572591738Z 2023-09-19  0:05:16 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2023-09-19T00:05:16.580119032Z 2023-09-19  0:05:16 0 [Note] InnoDB: Buffer pool(s) load completed at 230919  0:05:16
2023-09-19T00:05:16.584227363Z 2023-09-19  0:05:16 0 [Note] Server socket created on IP: '0.0.0.0'.
2023-09-19T00:05:16.584348904Z 2023-09-19  0:05:16 0 [Note] Server socket created on IP: '::'.
2023-09-19T00:05:16.611541947Z 2023-09-19  0:05:16 0 [Note] mariadbd: ready for connections.
2023-09-19T00:05:16.611673445Z Version: '10.11.5-MariaDB-1:10.11.5+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```
  
</details>

**Comment by alexjustesen** [comment]
At first glance it looks like the database came up slow. Try restarting the stack

**Comment by 1alessandro1** [comment]
That was indeed the case. Thanks.

I'm trying to change the time zone, I've ran the following:

```
# edit with vi docker-compose.yml and set it to Europe/Rome

sudo docker-compose down
sudo docker rmi <mariadb_image> <speedtest_tracker_image>

sudo docker-compose up -d
```
But still the database has UTC data and the new speedtest have still the UTC format. What am I missing?

**Comment by alexjustesen** [comment]
Going to close this initial issue but #689 might help with database timezones
