### ISSUE TITLE
V 0.12 (brand new) - when "Speedtest servers" Error 500

### ISSUE THREAD

**Issue by stanthewizzard** [alexjustesen/speedtest-tracker#789]
When trying to choose the server for speedtest
I got  error  500 and no server in the listing

```
#62 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#63 {main}
"} 
192.168.0.30 - - [19/Sep/2023:16:42:32 +0200] "POST /livewire/update HTTP/1.1" 500 6622 "https://XXX.YYY.COM/admin/general-page" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:42:53 +0200] "GET / HTTP/1.1" 302 282 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:42:54 +0200] "GET /admin HTTP/1.1" 302 414 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:42:55 +0200] "GET /admin/login HTTP/1.1" 200 32127 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:43:56 +0200] "GET / HTTP/1.1" 302 282 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:43:56 +0200] "GET /admin HTTP/1.1" 302 414 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:43:57 +0200] "GET /admin/login HTTP/1.1" 200 32127 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:44:58 +0200] "GET / HTTP/1.1" 302 282 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:44:59 +0200] "GET /admin HTTP/1.1" 302 414 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:45:00 +0200] "GET /admin/login HTTP/1.1" 200 32127 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:45:01 +0200] "POST /livewire/update HTTP/1.1" 200 11112 "https://XXX.YYY.COM/admin/general-page" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:13 +0200] "POST /livewire/update HTTP/1.1" 200 11151 "https://XXX.YYY.COM/admin/general-page" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:14 +0200] "POST /livewire/update HTTP/1.1" 200 1699 "https://XXX.YYY.COM/admin/general-page" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:15 +0200] "GET /admin HTTP/1.1" 200 13253 "https://XXX.YYY.COM/admin/general-page" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:17 +0200] "POST /livewire/update HTTP/1.1" 200 2625 "https://XXX.YYY.COM/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:19 +0200] "POST /livewire/update HTTP/1.1" 200 2643 "https://XXX.YYY.COM/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:20 +0200] "POST /livewire/update HTTP/1.1" 200 1703 "https://XXX.YYY.COM/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:23 +0200] "GET /admin/results HTTP/1.1" 200 15322 "https://XXX.YYY.COM/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:25 +0200] "POST /livewire/update HTTP/1.1" 200 2631 "https://XXX.YYY.COM/admin/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:29 +0200] "GET /admin/results HTTP/1.1" 200 15313 "https://XXX.YYY.COM/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:35 +0200] "GET /admin/results HTTP/1.1" 200 15314 "https://XXX.YYY.COM/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:45:37 +0200] "POST /livewire/update HTTP/1.1" 200 2628 
192.168.0.30 - - [19/Sep/2023:16:45:59 +0200] "GET /admin/results HTTP/1.1" 200 19100 "https://XXX.YYY.COM/admin/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
192.168.0.30 - - [19/Sep/2023:16:46:00 +0200] "POST /livewire/update HTTP/1.1" 200 2633 
192.168.0.30 - - [19/Sep/2023:16:46:01 +0200] "GET / HTTP/1.1" 302 282 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:46:02 +0200] "GET /admin HTTP/1.1" 302 414 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:46:03 +0200] "GET /admin/login HTTP/1.1" 200 32127 "-" "Uptime-Kuma/1.23.2"
192.168.0.30 - - [19/Sep/2023:16:46:03 +0200] "GET /admin/general-page HTTP/1.1" 200 20080 
192.168.0.30 - - [19/Sep/2023:16:46:05 +0200] "POST /livewire/update HTTP/1.1" 200 2635 "https://XXX.YYY.COM/admin/general-page" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
[2023-09-19 16:46:06] production.ERROR: App\Filament\Pages\Settings\GeneralPage::App\Filament\Pages\Settings\{closure}(): Argument #1 ($item) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 585 {"userId":1,"exception":"[object] (TypeError(code: 0): App\\Filament\\Pages\\Settings\\GeneralPage::App\\Filament\\Pages\\Settings\\{closure}(): Argument #1 ($item) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 585 at /var/www/html/app/Filament/Pages/Settings/GeneralPage.php:105)

[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(585): App\\Filament\\Pages\\Settings\\GeneralPage->App\\Filament\\Pages\\Settings\\{closure}()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(825): Illuminate\\Support\\Arr::mapWithKeys()
#2 /var/www/html/app/Filament/Pages/Settings/GeneralPage.php(105): Illuminate\\Support\\Collection->mapWithKeys()
#3 /var/www/html/app/Filament/Pages/Settings/GeneralPage.php(90): App\\Filament\\Pages\\Settings\\GeneralPage->getServerLabels()
#4 /var/www/html/vendor/filament/support/src/Concerns/EvaluatesClosures.php(35): App\\Filament\\Pages\\Settings\\GeneralPage->App\\Filament\\Pages\\Settings\\{closure}()
#5 /var/www/html/vendor/filament/forms/src/Components/Select.php(592): Filament\\Support\\Components\\Component->evaluate()
#6 /var/www/html/vendor/filament/forms/src/Components/Select.php(660): Filament\\Forms\\Components\\Select->getOptionLabels()
#7 /var/www/html/vendor/filament/forms/src/Concerns/SupportsSelectFields.php(37): Filament\\Forms\\Components\\Select->getOptionLabelsForJs()
#8 /var/www/html/vendor/filament/forms/src/Concerns/SupportsSelectFields.php(45): Filament\\Forms\\ComponentContainer->getSelectOptionLabels()
#9 /var/www/html/vendor/filament/forms/src/Concerns/SupportsSelectFields.php(45): Filament\\Forms\\ComponentContainer->getSelectOptionLabels()
#10 /var/www/html/vendor/filament/forms/src/Concerns/InteractsWithForms.php(76): Filament\\Forms\\ComponentContainer->getSelectOptionLabels()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Filament\\Pages\\BasePage->getFormSelectOptionLabels()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /var/www/html/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call()
#16 /var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(465): Livewire\\Wrapped->__call()
#17 /var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(108): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->callMethods()
#18 /var/www/html/vendor/livewire/livewire/src/LivewireManager.php(96): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#19 /var/www/html/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(85): Livewire\\LivewireManager->update()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#45 /var/www/html/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(89): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#62 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#63 {main}
"} 
```

Edit from @alexjustesen: fixed the format of the log so its easier to read.

**Comment by alexjustesen** [comment]
@stanthewizzard if you're in a fresh install where you don't care if settings/data get nuked can you run `php artisan app:install --force` from the container CLI and let me know if that fixes the issue? In the meantime I'll correct the type on this field.

**Comment by stanthewizzard** [comment]
I did

Starting to install the application...

⏳ Optimizing the cache...
✅ Optimized cache

⏳ Migrating the database...
✅ Database migrated

🚀 Finished installing the application!

Sadly same error 500

**Comment by stanthewizzard** [comment]
As the root password is randomized; I have no access to settings
ERROR 1044 (42000): Access denied for user 'speedy'@'%' to database 'settings'
:(

**Comment by alexjustesen** [comment]
> I can search in Speedtest servers but it is not automatically populated as in previous versions

Caught this comment so got that fixed in #796

**Comment by stanthewizzard** [comment]
Thanks

**Comment by stanthewizzard** [comment]
Updated and running perfectly !
