### ISSUE TITLE
500 Server Error - No application encryption key has been specified

### ISSUE THREAD

**Issue by Jbliske** [alexjustesen/speedtest-tracker#845]
**Describe the bug**

Getting a 500 Server Error after pulling the latest image.

Logs from container show this:

```
[2023-10-04 00:43:29] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)

#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()

#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(77): tap()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(60): Illuminate\\Encryption\\EncryptionServiceProvider->key()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\\Foundation\\Application->make()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
#18 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#19 {main}
```

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
-  Architecture: [e.g. arm64, amd64]
 - Version [e.g. v1]

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**

**Comment by colin-hall** [comment]
I've been having the same issue since v0.12.2 (and now on v0.13.1).  I'm running Docker version 24.0.6 on Debian 10 buster.

**Comment by alexjustesen** [comment]
@colin-hall in either your mounted directory or volume there is a `.env` file. Can you delete it and restart the container? 

Also worth noting, if you have vars in there you want to keep (i.e. SMTP config) copy the contents out and then add them to the newly generated file.

**Comment by colin-hall** [comment]
@alexjustesen Removing the `.env` file did the trick.  Starting up the container generated a differently-formatted `.env` file and I was able to plug in my custom SMTP values and everything's working.  

Thank you for your help and for the great work on this project!

**Comment by Jbliske** [comment]
> @Jbliske can you verify you're on `v0.13.1`? This version has a fix for the missing app key cache.
> 
> Also you can manually set a key following the faq [doc](https://docs.speedtest-tracker.dev/faqs#i-get-a-warning-on-container-start-up-that-the-app_key-is-missing) section.

I am running with the Latest tag; just updated the container this evening.

I followed the instructions you provided and it worked.  They APP_KEY was missing entirely so I added it with the key.

**Comment by alexjustesen** [comment]
@Jbliske it's also likely you have an old `.env` file which is enforcing a bad cache. I also recommend nuking it and letting it create a new one on startup.
