### ISSUE TITLE
Unable to start fresh docker container

### ISSUE THREAD

**Issue by ljlongwing** [alexjustesen/speedtest-tracker#862]
**Describe the bug**
I've been unable to run since the v0.13.1 image was released

**To Reproduce**
I have completely reset my image, running on Synology
I deleted the image, re-downloaded it, using 100% completely generic startup with no volumes mapped or anything, it should all be as OOTB as possible

**Expected behavior**
It should start

**Environment (please complete the following information):**
 - OS: Synology DS220+
-  Architecture: Docker
 - Browser NA
 - Version 0.13.1

**Logs**
SpeedtestTracker
date,stream,content
2023/10/10 10:56:10,stdout,prog: fatal: stopping the container.
2023/10/10 10:56:10,stdout,/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
2023/10/10 10:56:10,stdout,s6-rc: warning: unable to start service laravel-automations: command exited 1
2023/10/10 10:56:10,stdout,
2023/10/10 10:56:10,stdout,                                             
2023/10/10 10:56:10,stdout,  SQLSTATE[HY000] [2002] Connection refused  
2023/10/10 10:56:10,stdout,                                             
2023/10/10 10:56:10,stdout,In Connector.php line 65:
2023/10/10 10:56:10,stdout,
2023/10/10 10:56:10,stdout,                                                                               
2023/10/10 10:56:10,stdout,   migrations and table_type = 'BASE TABLE')                                   
2023/10/10 10:56:10,stdout,   from information_schema.tables where table_schema = forge and table_name =  
2023/10/10 10:56:10,stdout,"  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select *  
"
2023/10/10 10:56:10,stdout,                                                                               
2023/10/10 10:56:10,stdout,In Connection.php line 801:
2023/10/10 10:56:10,stdout,
2023/10/10 10:56:10,stdout,"} 
2023/10/10 10:56:10,stdout,#38 {main}
2023/10/10 10:56:10,stdout,#37 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
2023/10/10 10:56:10,stdout,#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
2023/10/10 10:56:10,stdout,#35 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
2023/10/10 10:56:10,stdout,#34 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
2023/10/10 10:56:10,stdout,#33 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
2023/10/10 10:56:10,stdout,#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
2023/10/10 10:56:10,stdout,#31 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
2023/10/10 10:56:10,stdout,#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
2023/10/10 10:56:10,stdout,#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
2023/10/10 10:56:10,stdout,#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
2023/10/10 10:56:10,stdout,#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
2023/10/10 10:56:10,stdout,#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
2023/10/10 10:56:10,stdout,#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
2023/10/10 10:56:10,stdout,#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
2023/10/10 10:56:10,stdout,#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
2023/10/10 10:56:10,stdout,#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
2023/10/10 10:56:10,stdout,#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
2023/10/10 10:56:10,stdout,#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): retry()
2023/10/10 10:56:10,stdout,#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
2023/10/10 10:56:10,stdout,#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
2023/10/10 10:56:10,stdout,#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
2023/10/10 10:56:10,stdout,#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
2023/10/10 10:56:10,stdout,#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(43): Illuminate\\Database\\Connection->selectFromWriteConnection()
2023/10/10 10:56:10,stdout,#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(394): Illuminate\\Database\\Connection->select()
2023/10/10 10:56:10,stdout,#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\\Database\\Connection->run()
2023/10/10 10:56:10,stdout,#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(757): Illuminate\\Database\\Connection->handleQueryException()
2023/10/10 10:56:10,stdout,#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(930): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection()
2023/10/10 10:56:10,stdout,#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(951): Illuminate\\Database\\Connection->runQueryCallback()
2023/10/10 10:56:10,stdout,#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(788): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
2023/10/10 10:56:10,stdout,#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\\Database\\Connection->getPdoForSelect()
2023/10/10 10:56:10,stdout,#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\\Database\\Connection->getPdo()
2023/10/10 10:56:10,stdout,#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1292): call_user_func()
2023/10/10 10:56:10,stdout,#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
2023/10/10 10:56:10,stdout,#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
2023/10/10 10:56:10,stdout,#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
2023/10/10 10:56:10,stdout,#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(48): Illuminate\\Database\\Connectors\\Connector->tryAgainIfCausedByLostConnection()
2023/10/10 10:56:10,stdout,#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(83): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
2023/10/10 10:56:10,stdout,#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
2023/10/10 10:56:10,stdout,[stacktrace]
2023/10/10 10:56:10,stdout,[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)
2023/10/10 10:56:10,stdout,
2023/10/10 10:56:10,stdout,#28 {main}
2023/10/10 10:56:10,stdout,#27 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
2023/10/10 10:56:10,stdout,#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
2023/10/10 10:56:10,stdout,#25 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
2023/10/10 10:56:10,stdout,#24 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
2023/10/10 10:56:10,stdout,#23 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
2023/10/10 10:56:10,stdout,#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
2023/10/10 10:56:10,stdout,#21 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
2023/10/10 10:56:10,stdout,#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
2023/10/10 10:56:10,stdout,#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
2023/10/10 10:56:10,stdout,#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
2023/10/10 10:56:10,stdout,#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
2023/10/10 10:56:10,stdout,#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
2023/10/10 10:56:10,stdout,#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
2023/10/10 10:56:10,stdout,#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
2023/10/10 10:56:10,stdout,#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
2023/10/10 10:56:10,stdout,#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
2023/10/10 10:56:10,stdout,#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
2023/10/10 10:56:10,stdout,#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): retry()
2023/10/10 10:56:10,stdout,#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
2023/10/10 10:56:10,stdout,#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
2023/10/10 10:56:10,stdout,#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
2023/10/10 10:56:10,stdout,#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
2023/10/10 10:56:10,stdout,#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(43): Illuminate\\Database\\Connection->selectFromWriteConnection()
2023/10/10 10:56:10,stdout,#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(394): Illuminate\\Database\\Connection->select()
2023/10/10 10:56:10,stdout,#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\\Database\\Connection->run()
2023/10/10 10:56:10,stdout,#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(757): Illuminate\\Database\\Connection->handleQueryException()
2023/10/10 10:56:10,stdout,#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(930): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection()
2023/10/10 10:56:10,stdout,#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(951): Illuminate\\Database\\Connection->runQueryCallback()
2023/10/10 10:56:10,stdout,[stacktrace]
2023/10/10 10:56:10,stdout,"[2023-10-10 16:56:10] production.ERROR: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE') {\"exception\":\"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE') at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:801)
"
2023/10/10 10:56:10,stdout,🚛  Migrating the database...
2023/10/10 10:56:10,stdout,
2023/10/10 10:56:10,stdout,✅  Cache set.
2023/10/10 10:56:09,stdout,💰  Building the cache...
2023/10/10 10:56:09,stdout,
2023/10/10 10:56:09,stdout,"👀  To set an application key that persists, read the docs: https://docs.speedtest-tracker.dev/
"
2023/10/10 10:56:09,stdout,"⚠️  An application key was generated at start up, no environment variable was set.
"
2023/10/10 10:56:08,stdout,⏳  Generating an application key...
2023/10/10 10:56:08,stdout,
2023/10/10 10:56:08,stdout,✅  Symlinks created.
2023/10/10 10:56:08,stdout,🔗  Creating symlinks for config and log files...
2023/10/10 10:56:08,stdout,
2023/10/10 10:56:08,stdout,✅  Environment file created.
2023/10/10 10:56:08,stdout,"🙄  Environment file not found, creating...
"
2023/10/10 10:56:08,stdout,
2023/10/10 10:56:08,stdout,✅  Database symlink created.
2023/10/10 10:56:08,stdout,🔗  Creating database symlink...
2023/10/10 10:56:08,stdout,
2023/10/10 10:56:08,stdout,✅  Cache cleared.
2023/10/10 10:56:01,stdout,🧹  Clearing any previous caches...
2023/10/10 10:56:01,stdout,
2023/10/10 10:56:01,stdout,✅  Permissions fixed.
2023/10/10 10:56:01,stdout,🔒  Fixing app path file permissions...
2023/10/10 10:56:01,stdout,
2023/10/10 10:56:01,stdout,🐇  Configuring Speedtest Tracker...
2023/10/10 10:56:01,stdout,
2023/10/10 10:56:01,stdout,-----
2023/10/10 10:56:01,stdout,.+...+...+....+........+...+.+...+...+........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+.+...........+...+......+.+.....+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*......+..+......+.......+..+...+.+..+....+...+.....+...+...+....+..+.........+.+.........+............+.........+.....+.+............+.....+.+..+...................+...+...+.....+....+.....+.+...+......+.....+...+...+....+...............+.....+....+.....+......+...+...+.............+.....+....+......+.....+.+...+..+.........+......+.+............+.....+......+.+......+...+..............+.+..+.......+..+......+....+...+.....+.+..+...+......+...+.+......+......+.....+.......+.....+..........+........+..........+............+........+.............+.....+.+...+..+.+..............+..........+......+..+............+....+.........+..+.+..+.+......+.....+......+..................+.+.....+....+......+.........+.....+....+.....+...+...+....+...........+.......+..+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2023/10/10 10:56:00,stdout,......+.....+....+...........+.+.....+.......+......+..+............+......+.+......+..+.+.....+............+.........+.+.........+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+....+........+.............+..+......+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+....+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2023/10/10 10:56:00,stdout,"🏃‍♂️ An SSL key was not detected, so I'll generate a self-signed SSL certificate pair for you...
"
2023/10/10 10:56:00,stdout,"🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
"
2023/10/10 10:56:00,stdout,
2023/10/10 10:56:00,stdout,-------------------------------------
2023/10/10 10:56:00,stdout,User gid:    9999
2023/10/10 10:56:00,stdout,User uid:    9999
2023/10/10 10:56:00,stdout,
2023/10/10 10:56:00,stdout,-------------------------------------
2023/10/10 10:56:00,stdout,GID/UID
2023/10/10 10:56:00,stdout,-------------------------------------
2023/10/10 10:56:00,stdout,https://github.com/alexjustesen/speedtest-tracker
2023/10/10 10:56:00,stdout,To support Speedtest Tracker visit:
2023/10/10 10:56:00,stdout,
2023/10/10 10:56:00,stdout,--------------------------------------------------------------------
2023/10/10 10:56:00,stdout,
2023/10/10 10:56:00,stdout,
2023/10/10 10:56:00,stdout,  |___|  |__| |___._|____||__|__|_____|__|
2023/10/10 10:56:00,stdout,  |   |  |   _|  _  |  __||    <|  -__|   _|
2023/10/10 10:56:00,stdout,|_     _|.----.---.-.----.|  |--.-----.----.
2023/10/10 10:56:00,stdout, _______                   __
2023/10/10 10:56:00,stdout,         |__|
2023/10/10 10:56:00,stdout,|_______||   __|_____|_____|_____|____|_____|_____||____|
2023/10/10 10:56:00,stdout,|__     ||  _  |  -__|  -__|  _  |   _|  -__|__ --||   _|
2023/10/10 10:56:00,stdout,|     __|.-----.-----.-----.--|  |  |_.-----.-----.|  |_
2023/10/10 10:56:00,stdout, _______                       __ __                __
2023/10/10 10:56:00,stdout,
2023/10/10 10:56:00,stdout,--------------------------------------------------------------------
2023/10/10 10:56:00,stdout,

**Comment by vstrong-info** [comment]
I have the same issue on a newly deployed Speedtest Tracker container. It fails at 'Migrating the database':

**Synology DS412+
Docker 20.10.3-0554**

🚛  Migrating the database...
--
production.ERROR: SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE') at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:801)
--
[stacktrace]
--
#0 to #28 /var etc etc skipped

[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)

SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from information_schema.tables where table_schema = forge and table_name =  migrations and table_type = 'BASE TABLE')                                                                                                                   

In Connector.php line 65:

SQLSTATE[HY000] [2002] Connection refused

s6-rc: warning: unable to start service laravel-automations: command exited 1 /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

prog: fatal: stopping the container.

**Comment by alexjustesen** [comment]
This means your DB environment variables aren't correct. Make sure they're either passed as environment variables in your docker command or in `.env` file. But they should only be in one of those locations.

I can't help much without `docker-compose.yml` file contents being shared unfortunately.

**Comment by vstrong-info** [comment]
Here is my docker command:
```
docker run -d --name speedtest-tracker --restart unless-stopped \
    -p 8080:80 \
    -p 8443:443 \
    -e PUID=1026 \
    -e PGID=100 \
    -e TZ=Europe/London \
    -v /etc/localtime:/etc/localtime:ro \
    -v /volume1/docker/speedtest:/config \
    -v /volume1/docker/speedtest:/etc/ssl/web \
    ghcr.io/alexjustesen/speedtest-tracker:latest

```

**Comment by alexjustesen** [comment]
You'll need to set your DB variables there https://docs.speedtest-tracker.dev/getting-started/installation/installation#install-with-docker

**Comment by vstrong-info** [comment]
Thank you @alexjustesen
Does this mean we can add all these parameters with blank values and the database will be created automatically? Or we have to have an external database? Thank you.
```
    -e DB_CONNECTION=mysql \
    -e DB_HOST= \
    -e DB_PORT=3306 \
    -e DB_DATABASE=speedtest_tracker \
    -e DB_USERNAME= \
    -e DB_PASSWORD= \
```

**Comment by alexjustesen** [comment]
SQLite is no longer recommended but you can still use it as it's supported by the underlying framework. I strongly suggest using a MySQL/MariaDB/Postgres database though.

If you want to use sqlite still you can pass the following:

```
DB_CONNECTION=sqlite
DB_DATABASE=/config/database.sqlite
```
