### ISSUE TITLE
Error 500... can't access control panel

### ISSUE THREAD

**Issue by Jaxel** [alexjustesen/speedtest-tracker#865]
I looked at previous bug reports, and they all say it's related to a missing `app_key` in the `.env` file. My `.env` file has an `app_key` already and replacing it has made no difference.

```
2023/10/12 06:59:55	stdout	172.17.0.1 - - [12/Oct/2023:06:59:55 -0400] "GET /api/speedtest/latest HTTP/1.1" 200 398 "-" "-"
2023/10/12 06:59:55	stderr	"} 
2023/10/12 06:59:55	stderr	#19 {main}
2023/10/12 06:59:55	stderr	#18 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
2023/10/12 06:59:55	stderr	#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
2023/10/12 06:59:55	stderr	#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\\Foundation\\Application->make()
2023/10/12 06:59:55	stderr	#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
2023/10/12 06:59:55	stderr	#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
2023/10/12 06:59:55	stderr	#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
2023/10/12 06:59:55	stderr	#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
2023/10/12 06:59:55	stderr	#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
2023/10/12 06:59:55	stderr	#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
2023/10/12 06:59:55	stderr	#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
2023/10/12 06:59:55	stderr	#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
2023/10/12 06:59:55	stderr	#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
2023/10/12 06:59:55	stderr	#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
2023/10/12 06:59:55	stderr	#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
2023/10/12 06:59:55	stderr	#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
2023/10/12 06:59:55	stderr	#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()
2023/10/12 06:59:55	stderr	#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(60): Illuminate\\Encryption\\EncryptionServiceProvider->key()
2023/10/12 06:59:55	stderr	#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(77): tap()
2023/10/12 06:59:55	stderr	#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
2023/10/12 06:59:55	stderr	[stacktrace]
2023/10/12 06:59:55	stderr	[2023-10-12 10:59:55] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
```

**Comment by rmotapar** [comment]
I am seeing the same error. Tried regenerating the key and updating APP_KEY but I see the same error as in the above comment.

**Comment by alexjustesen** [comment]
Did you generate an app key, place it into the `.env` file and restart the container?

**Comment by Jaxel** [comment]
Yes. Putting a new app_key in `.env` and restarting made no difference...

However, I did solve the issue by putting the app_key in my `docker-compose.yaml`.

**Comment by alexjustesen** [comment]
Correct you can only have it in one location. Now that I have some time again I'll get that fixed and added to the docs where you should be using `docker-compose.yml` vars or `.env` file and not both.

**Comment by Jaxel** [comment]
> Correct you can only have it in one location. Now that I have some time again I'll get that fixed and added to the docs where you should be using `docker-compose.yml` vars or `.env` file and not both.

No, that's not correct. I originally had it only in `.env`... it did not work. Error 500.

Now I have it in BOTH, and it works. No errors.
