### ISSUE TITLE
Losing network connection on server and speedtest fails

### ISSUE THREAD

**Issue by NorskNoobing** [alexjustesen/speedtest-tracker#995]
**Describe the bug**
Every time a speedtest runs (both manual and scheduled) my server seemingly loses network connection for a couple of seconds. I haven't been able to confirm if I lose network connection altogether, but I believe that I do, because I lose connection to both my Minecraft server and my VSCode remote SSH session at the same time.

This has been an issue for a while, but I'm unsure when it first happened. It could've started an update, but that I can't confirm.

The data logs in the web-UI mention using the path `/root/.config/ookla/speedtest-cli.json`, but I checked the `/root` path in the container, and there wasn't any files there.

<details>
<summary>docker-compose.yml</summary>
  
```yml
# SPEEDTEST-TRACKER
  speedtest-tracker:
    container_name: speedtest-tracker
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=speedtest
      - DB_PASSWORD=$SPEEDTEST_DB_PASSWORD
      - MAIL_HOST=$MAIL_HOST
      - MAIL_PORT=$MAIL_PORT
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$SPEEDTEST_MAIL_PASSWORD
      - MAIL_FROM_ADDRESS=$MAIL_USERNAME
    volumes:
      - $DATA/speedtest-tracker:/config
    labels:
      - traefik.enable=true
      - traefik.http.services.speedtest-tracker.loadbalancer.server.port=443
      - traefik.http.services.speedtest-tracker.loadbalancer.server.scheme=https
      - traefik.http.routers.speedtest-tracker.rule=Host(`speedtest.$DOMAIN`)
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - default-network
```
</details>

**To Reproduce**
Just use the docker compose, and run a speedtest or wait for the scheduled one.

**Environment (please complete the following information):**
 - OS: Ubuntu
-  Architecture: amd64
 - Browser: N/A
 - App version: 0.14.0

**Screenshots**
<img width=500px src="https://github.com/alexjustesen/speedtest-tracker/assets/39239702/c3169f79-cd0e-420e-b940-1879efa07f84"/></img>

**Logs**
<details>
  <summary>Docker container logs</summary>

```
2023-12-20T09:18:16.920139305Z [2023-12-20 09:18:16] production.ERROR: absoluteDownloadThresholdFailed(): Argument #2 ($download) must be of type float, null given, called in /var/www/html/app/Listeners/Threshold/AbsoluteListener.php on line 117 {"exception":"[object] (TypeError(code: 0): absoluteDownloadThresholdFailed(): Argument #2 ($download) must be of type float, null given, called in /var/www/html/app/Listeners/Threshold/AbsoluteListener.php on line 117 at /var/www/html/app/helpers.php:37)
2023-12-20T09:18:16.920177731Z [stacktrace]
2023-12-20T09:18:16.920182909Z #0 /var/www/html/app/Listeners/Threshold/AbsoluteListener.php(117): absoluteDownloadThresholdFailed()
2023-12-20T09:18:16.920186384Z #1 /var/www/html/app/Listeners/Threshold/AbsoluteListener.php(56): App\\Listeners\\Threshold\\AbsoluteListener->mailChannel()
2023-12-20T09:18:16.920190152Z #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(107): App\\Listeners\\Threshold\\AbsoluteListener->handle()
2023-12-20T09:18:16.920193511Z #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Events\\CallQueuedListener->handle()
2023-12-20T09:18:16.920197124Z #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
2023-12-20T09:18:16.920200460Z #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
2023-12-20T09:18:16.920203733Z #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
2023-12-20T09:18:16.920206908Z #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
2023-12-20T09:18:16.920210101Z #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
2023-12-20T09:18:16.920221682Z #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
2023-12-20T09:18:16.920225342Z #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-12-20T09:18:16.920229756Z #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
2023-12-20T09:18:16.920233016Z #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()
2023-12-20T09:18:16.920236330Z #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
2023-12-20T09:18:16.920239748Z #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-12-20T09:18:16.920243185Z #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
2023-12-20T09:18:16.920246380Z #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
2023-12-20T09:18:16.920254628Z #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
2023-12-20T09:18:16.920258130Z #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
2023-12-20T09:18:16.920261406Z #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
2023-12-20T09:18:16.920264635Z #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
2023-12-20T09:18:16.920267814Z #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon()
2023-12-20T09:18:16.920270955Z #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
2023-12-20T09:18:16.920274276Z #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
2023-12-20T09:18:16.920277495Z #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
2023-12-20T09:18:16.920280869Z #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
2023-12-20T09:18:16.920284379Z #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
2023-12-20T09:18:16.920287656Z #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
2023-12-20T09:18:16.920290872Z #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
2023-12-20T09:18:16.920294048Z #29 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
2023-12-20T09:18:16.920297235Z #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
2023-12-20T09:18:16.920300528Z #31 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
2023-12-20T09:18:16.920303663Z #32 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
2023-12-20T09:18:16.920306994Z #33 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
2023-12-20T09:18:16.920310182Z #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
2023-12-20T09:18:16.920313384Z #35 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
2023-12-20T09:18:16.920316606Z #36 {main}
2023-12-20T09:18:16.920319510Z "} 
```
</details>

**Comment by alexjustesen** [comment]
So `production.ERROR: absoluteDownloadThresholdFailed()` is related to #881, currently there's a bug where it tries to assess sending a notification when there is no result.

It's interesting how your network is dropping connection when a speedtest is run... Can you try the following steps and let me know the outcome? Also looking for logs that don't reference the download threshold from above.

1. Open the container's terminal to run commands
2. Run `speedtest --accept-license`, this will trigger the Speedtest CLI
3. This should run in the terminal with download and upload outputs

**Comment by NorskNoobing** [comment]
I've disabled the threshold. 

# CLI command
When I tried running the CLI command. After running the command it seems to work fine for the first couple of percent (the first time it stopped at 4% and the 2nd at 8%):
![image](https://github.com/alexjustesen/speedtest-tracker/assets/39239702/94da4d56-cb94-4ca2-9ff8-6e41a49209ce)

But then it suddenly stops, I temporarily lose connection to the server, and the CLI output says `Cannot open socket`:
![image](https://github.com/alexjustesen/speedtest-tracker/assets/39239702/9f077fb5-f2cf-4119-9737-af0c4e95923f)

# Manual run from web
I got the same message as before when manually running a speedtest from the web-UI.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/39239702/e6a6f201-5c0b-4a74-bf7f-0f8097f57cc5)

The docker container logs doesn't mention anything about the run now that the threshold is disabled. The only things in the container logs are the requests for the admin panel from my browser, so no errors there.

**Comment by alexjustesen** [comment]
> The docker container logs doesn't mention anything about the run now that the threshold is disabled. The only things in the container logs are the requests for the admin panel from my browser, so no errors there.

This is good at least from my app's stand point this means the error isn't there. Are you able to run speedtests in the browser without your connection dying?

**Comment by NorskNoobing** [comment]
Yeah, the network test via speedtest.net works just fine, with expected speeds. 
![image](https://github.com/alexjustesen/speedtest-tracker/assets/39239702/882319c5-a3ff-4a3a-90c9-f627712221c9)

I think I'll try with another docker network config, but if you have any suggestions I'll be happy to test anything.

**Comment by alexjustesen** [comment]
Yeah this is a new one, after changing the docker network I'd also try searching the logs on your host machine and your router to see if any clues might be there.

I'm going to transfer this issue to a discussion so please keep the updates coming on your findings and I'll open a new issue if we can target something concrete.
