### ISSUE TITLE
Docker Installation fails

### ISSUE THREAD

**Issue by s4en** [alexjustesen/speedtest-tracker#997]
My Installation with the Docker Compose fails.
I've tried 3 different Compose Files, made 3 times new Volumes and get everytime the same Error.
Any Idea, the old Version made by Henry has work all time.

```
In Connection.php line 822:

                                                                               

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed:  

   Temporary failure in name resolution (Connection: mysql, SQL: select table  

  _name as `name`, (data_length + index_length) as `size`, table_comment as `  

  comment`, engine as `engine`, table_collation as `collation` from informati  

  on_schema.tables where table_schema = 'speedtest' and table_type = 'BASE TA  

  BLE' order by table_name)                                                    

                                                                               

In Connector.php line 65:

                                                                               

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed:  

   Temporary failure in name resolution                                        

                                                                               

In Connector.php line 65:

                                                                               

  PDO::__construct(): php_network_getaddresses: getaddrinfo for db failed: Te  

  mporary failure in name resolution                                           

                                                                               

s6-rc: warning: unable to start service laravel-automations: command exited 1

/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

prog: fatal: stopping the container.
```

```
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#22 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#24 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#25 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#26 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#28 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#29 {main}
[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Temporary failure in name resolution at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)
      
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(83): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(48): Illuminate\\Database\\Connectors\\Connector->tryAgainIfCausedByLostConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1319): call_user_func()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\\Database\\Connection->getPdo()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\\Database\\Connection->getPdoForSelect()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(976): Illuminate\\Database\\Connection->runQueryCallback()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(955): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(778): Illuminate\\Database\\Connection->handleQueryException()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\\Database\\Connection->run()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(394): Illuminate\\Database\\Connection->select()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(41): Illuminate\\Database\\Connection->selectFromWriteConnection()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(162): Illuminate\\Database\\Schema\\MySqlBuilder->getTables()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\Builder->hasTable()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): retry()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#32 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#34 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#35 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#36 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#38 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#39 {main}
[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo for db failed: Temporary failure in name resolution at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)
      
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(83): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(48): Illuminate\\Database\\Connectors\\Connector->tryAgainIfCausedByLostConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1319): call_user_func()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\\Database\\Connection->getPdo()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\\Database\\Connection->getPdoForSelect()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(976): Illuminate\\Database\\Connection->runQueryCallback()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(955): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(778): Illuminate\\Database\\Connection->handleQueryException()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\\Database\\Connection->run()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(394): Illuminate\\Database\\Connection->select()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(41): Illuminate\\Database\\Connection->selectFromWriteConnection()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(162): Illuminate\\Database\\Schema\\MySqlBuilder->getTables()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\Builder->hasTable()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): retry()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#32 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#34 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#35 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#36 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#38 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#39 {main}
"} 
s6-rc: warning: unable to start service laravel-automations: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
```

**My Docker Compose/Stack**

```
version: '3.9'
services:
    speedtest-tracker:
        image: ghcr.io/alexjustesen/speedtest-tracker:latest
        container_name: Speedtest
        healthcheck:
         test: curl -f http://localhost:80/ || exit 1
        environment:
             PUID: 1000
             PGID: 1000
             DB_CONNECTION: mysql
             DB_HOST: db
             DB_PORT: 3306
             DB_DATABASE: speedtest
             DB_USERNAME: Name
             DB_PASSWORD: Password
        volumes:
            - speedtest:/config:rw
        ports:
            - 8080:80
            
        restart: on-failure:5
        depends_on:
            - db
    db:
        image: mariadb:jammy
        container_name: Speedtest-DB
        mem_limit: 1g
        cpu_shares: 768
        security_opt:
            - no-new-privileges:false
        user: 1000:1000
        environment:
           TZ: Europe/Berlin
           MARIADB_DATABASE: speedtest
           MARIADB_USER: Name
           MARIADB_PASSWORD: Password
           MARIADB_ROOT_PASSWORD: Password
        volumes:
          - speedtestsql:/var/lib/mysql:rw
          - speedtest:/etc/mysql/conf.d:rw
        restart: on-failure:5
volumes:
  speedtest:
    external: true
  speedtestsql:
     external: true
```

**Comment by alexjustesen** [comment]
At first glance the compose file looks fine, try browsing the files in the speedtest volume and specifically look for `.env` and make sure there are no `DB_` prefix variables there.

**Comment by s4en** [comment]
So I've check the .env and made a completly new volume. Also Error but i think there is something with the permission of the database
```
In Connection.php line 801:

                                                                               

  SQLSTATE[HY000] [1130] Host '192.168.XX.X' is not allowed to connect to thi  

  s MariaDB server (Connection: mysql, SQL: select * from information_schema.  

  tables where table_schema = speedtest_tracker and table_name = migrations a  

  nd table_type = 'BASE TABLE')                                                

                                                                               

In Connector.php line 65:

                                                                               

  SQLSTATE[HY000] [1130] Host '192.168.XX.X' is not allowed to connect to thi  

  s MariaDB server                                                             

                                                                               

s6-rc: warning: unable to start service laravel-automations: command exited 1

/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

prog: fatal: stopping the container.

```

**Comment by alexjustesen** [comment]
Try dropping the database's `user:` config?

**Comment by s4en** [comment]
Delete all DB user and passwords, same error. That makes no sense for me. The databse creates a network and the IP ist other than of the normal container. Is this right?

**Comment by nsk** [comment]
Hello I followed your docker compose, when I arrive on the connection page it asks me for an email and password except this is not entered in the compose

http://192.168.1.23:8080/admin/login

**Comment by nsk** [comment]
hi , 

the configuration for progesql is the same?? 

thx

**Comment by s4en** [comment]
> So I ran the following dropping `user: 1000:1000` and it came up for me. I'm also locally creating the volumes in this case as I don't have an external FS to test against.
> 
> ```
> version: '3.9'
> services:
>     speedtest-tracker:
>         image: ghcr.io/alexjustesen/speedtest-tracker:latest
>         container_name: Speedtest
>         healthcheck:
>          test: curl -f http://localhost:80/ || exit 1
>         environment:
>              PUID: 1000
>              PGID: 1000
>              DB_CONNECTION: mysql
>              DB_HOST: db
>              DB_PORT: 3306
>              DB_DATABASE: speedtest
>              DB_USERNAME: Name
>              DB_PASSWORD: Password
>         volumes:
>             - 997speedtest:/config:rw
>         ports:
>             - 8080:80
>         restart: on-failure:5
>         depends_on:
>             - db
>     db:
>         image: mariadb:jammy
>         container_name: Speedtest-DB
>         mem_limit: 1g
>         cpu_shares: 768
>         security_opt:
>             - no-new-privileges:false
>         environment:
>            TZ: Europe/Berlin
>            MARIADB_DATABASE: speedtest
>            MARIADB_USER: Name
>            MARIADB_PASSWORD: Password
>            MARIADB_ROOT_PASSWORD: Password
>         volumes:
>           - 997speedtestsql:/var/lib/mysql:rw
>           - 997speedtest:/etc/mysql/conf.d:rw
>         restart: on-failure:5
> volumes:
>   997speedtest:
>   997speedtestsql:
> ```

So i think i know it now. I use a NFS Volume for config and Database. When i use a locally drive directly inside the host it works.

**Comment by alexjustesen** [comment]
> So i think i know it now. I use a NFS Volume for config and Database. When i use a locally drive directly inside the host it works.

I been meaning to get Docker Swarm and K8s docs written so I'm going to add external volumes to that as well as it's a common use case in that architecture.

Closing the issue but have it tracked, thanks for helping narrow it down.

**Comment by s4en** [comment]
Maybe interessing for someone else. I created a container with a mariadb database with binding the nfs volume. 
Than i use this database in speedtracker compose file and that works. So maybe for some people with the same error.

**Comment by istrait** [comment]
I am having the same issue installing on a synology server.  Neither of the sets of docer compose files allow the speedtest image to connect to the database image.

This is the error.

In Connection.php line 822:
                                                                               
  SQLSTATE[08006] [7] connection to server at "db" (172.31.0.3), port 5432 fa  
  iled: Connection refused                                                     
  	Is the server running on that host and accepting TCP/IP connections? (Conn   
  ection: pgsql, SQL: select * from information_schema.tables where table_cat  
  alog = speedtest_tracker and table_schema = public and table_name = migrati  
  ons and table_type = 'BASE TABLE')                                           
                                                                               
In Connector.php line 65:
                                                                               
  SQLSTATE[08006] [7] connection to server at "db" (172.31.0.3), port 5432 fa  
  iled: Connection refused                                                     
  	Is the server running on that host and accepting TCP/IP connections?     

I see that others have fixed this.

Here is my docker compose.

version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8080:80'
            - '8443:443'
        environment:
            - PUID=100
            - PGID=1026
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - speedtest-app:/config
            - '/volume1/docker/speedtest/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: postgres:15
        restart: always
        environment:
            - POSTGRES_DB=speedtest_tracker
            - POSTGRES_USER=speedy
            - POSTGRES_PASSWORD=password
        volumes:
            - speedtest-db:/var/lib/postgresql/data
volumes:
    speedtest-app:
    speedtest-db:

How can I fix this?

**Comment by nsk** [comment]
Installed on portainer for me no issues or problem whit you compose , is done ! Thx

**Comment by hoorna** [comment]
@istrait, in your compose file a port definition is missing for the db: service. Probably the port definition it has to be:
    ports:
    - '5432:5432'

**Comment by istrait** [comment]
Thanks for the suggestions, but I am still getting an error.
Depoloyng this in portainer (With port for database server now.)

```
version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - '8765:80'
            - '8465:443'
        environment:
            - PUID=100
            - PGID=1026
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5431
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - speedtest-app:/config
            - '/volume1/docker/speedtest/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: postgres:15
        restart: always
        ports:
            - '5431:5432'
        environment:
            - POSTGRES_DB=speedtest_tracker
            - POSTGRES_USER=speedy
            - POSTGRES_PASSWORD=password
        volumes:
            - speedtest-db:/var/lib/postgresql/data
volumes:
    speedtest-app:
    speedtest-db:
```

I get this error in the logs.

```
In Connection.php line 822:
                                                                               
  SQLSTATE[08006] [7] could not translate host name "db" to address: Name or   
  service not known (Connection: pgsql, SQL: select * from information_schema  
  .tables where table_catalog = speedtest_tracker and table_schema = public a  
  nd table_name = migrations and table_type = 'BASE TABLE')          
```
When I look at the networks in portainer, speedtest-db is not grabbing an ip.

What should I check next?

I am also getting this from the speedtest-db container

```
`The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
initdb: hint: If you want to create a new database system, either remove or empty the directory "/var/lib/postgresql/data" or run initdb with an argument other than "/var/lib/postgresql/data".
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.`
```

**Comment by hoorna** [comment]
@istrait, the error message in the speedtest container tells you that it was not possible to translate the host "db" to an network IP address. At the environment variable DB_HOST you have to fill in the IP address from the host which the db container is running on (if you are using the network mode "host") or the IP address from the db container (if you are using the network mode "bridge").

I recommend that you learn more into Docker Compose and how the Compose commands work. The issues you encounter can easily be avoided with a little more knowledge.
